-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versi server:                 10.1.37-MariaDB - mariadb.org binary distribution
-- OS Server:                    Win32
-- HeidiSQL Versi:               9.4.0.5125
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- membuang struktur untuk table erp_privi.employee
CREATE TABLE IF NOT EXISTS `employee` (
  `cNip` char(7) NOT NULL COMMENT 'Nomer induk Pegawai',
  `vName` varchar(30) DEFAULT '' COMMENT 'Nama pegawai',
  `vNickName` varchar(15) DEFAULT NULL COMMENT 'Nama panggilan',
  `cUpper` char(7) DEFAULT NULL COMMENT 'NIP Atasan',
  `iCompanyID` int(2) NOT NULL DEFAULT '0' COMMENT 'kode perusahaan',
  `iDeptID` int(2) NOT NULL DEFAULT '0' COMMENT 'kode departemen',
  `iDivID` int(2) DEFAULT '0' COMMENT 'kode divisi',
  `ibagid` int(2) DEFAULT NULL COMMENT 'kode bagian',
  `iPostID` int(3) DEFAULT '0' COMMENT 'kode jabatan',
  `iArea` int(3) DEFAULT '0',
  `iWorkArea` int(2) DEFAULT '0' COMMENT 'kode area kerja relasi ke tbl: worklocation',
  `iAreaFrom` int(3) DEFAULT '0',
  `dIn` date DEFAULT '0000-00-00' COMMENT 'tgl bergabung',
  `dRealIn` date DEFAULT '0000-00-00' COMMENT 'tgl bergabung',
  `dPassProbation` date DEFAULT '0000-00-00' COMMENT 'tgl penentuan masa percobaan',
  `dPermanent` date DEFAULT '0000-00-00' COMMENT 'tgl pengangkatan permanen',
  `cFlag` char(1) DEFAULT NULL COMMENT 'status karyawan C: contract, O:outsource',
  `iWorkID` int(2) DEFAULT NULL,
  `cTaxCode` char(2) DEFAULT NULL COMMENT 'kode pajak',
  `cTaxNumber` char(40) DEFAULT NULL COMMENT 'nomer wajib pajak',
  `dSosSecurity` date DEFAULT '0000-00-00',
  `vSosSecurity` varchar(30) DEFAULT NULL,
  `cPayType` char(2) DEFAULT NULL,
  `cPayCode` char(1) DEFAULT NULL,
  `cPayStatus` char(1) DEFAULT NULL,
  `lOvrTime` bit(1) DEFAULT NULL,
  `iBankID` int(2) DEFAULT NULL COMMENT 'status apakah memiliki no account bank atau tidak',
  `vAccNumber` varchar(20) DEFAULT NULL COMMENT 'no account bank yang dimiliki',
  `vBankBranch` varchar(50) DEFAULT NULL COMMENT 'Cabang rekening bank',
  `vBankCity` varchar(20) DEFAULT NULL COMMENT 'lokasi bank',
  `lSimpapi` bit(1) DEFAULT NULL,
  `lKesgapi` bit(1) DEFAULT NULL,
  `vIdNumber` varchar(50) DEFAULT NULL COMMENT 'no  identitas KTP',
  `DIdExpired` date DEFAULT '0000-00-00' COMMENT 'tgl expired KTP',
  `vBirthPlace` varchar(40) DEFAULT NULL COMMENT 'tempat lahir',
  `dBirthday` date DEFAULT '0000-00-00' COMMENT 'tgl ultah',
  `vCitizen` varchar(3) DEFAULT NULL COMMENT 'warga negara',
  `vMother` varchar(30) DEFAULT NULL COMMENT 'Nama ibu kandung',
  `iReligion` int(2) DEFAULT NULL COMMENT 'agama',
  `vBloodType` varchar(2) DEFAULT NULL COMMENT 'Jenis darah',
  `vEmail` varchar(50) DEFAULT NULL COMMENT 'email',
  `iFoodID` int(2) DEFAULT NULL COMMENT 'kode makanan fav?',
  `iTransID` int(2) DEFAULT NULL COMMENT 'kode transportasi yang digunakan?',
  `cEmpStat` char(1) DEFAULT NULL COMMENT 'status karyawan tetap atau tidak',
  `vIDAddress` varchar(100) DEFAULT NULL COMMENT 'alamat sesuai KTP',
  `vIDBlock` varchar(15) DEFAULT NULL COMMENT 'blok rumah sesuai KTP',
  `vIDLot` varchar(3) DEFAULT NULL COMMENT 'Lot rumah sesuai KTP',
  `viDHomeNo` varchar(4) DEFAULT NULL COMMENT 'No rumah sesuai KTP',
  `vIDKelurahan` varchar(50) DEFAULT NULL COMMENT 'Kelurahan tempat tinggal sesuai KTP',
  `vIDKecamatan` varchar(50) DEFAULT NULL COMMENT 'Kecamatan tempat tinggal sesuai KTP',
  `vIDKotamadya` varchar(30) DEFAULT NULL COMMENT 'Kotamadya tempat tinggal sesuai KTP',
  `cIDPostal` char(5) DEFAULT NULL COMMENT 'kode pos tempat tinggal sesuai KTP',
  `vIDPhoneCode` varchar(4) DEFAULT NULL COMMENT 'Kode area sesuai KTP',
  `vIDPhoneNumber` varchar(20) DEFAULT NULL COMMENT 'No tlp yang bisa dihubungi sesuai KTP',
  `vStAddress` varchar(100) DEFAULT NULL COMMENT 'Alamat  ',
  `vStKelurahan` varchar(50) DEFAULT NULL COMMENT 'Kelurahan tempat tinggal',
  `vStKecamatan` varchar(50) DEFAULT NULL COMMENT 'Kecamatan tempat tinggal ',
  `vStKotamadya` varchar(30) DEFAULT NULL COMMENT 'Kotamadya tempat tinggal',
  `cStPostal` char(5) DEFAULT NULL COMMENT 'Kode pos tempat tinggal',
  `vStPhoneCode` varchar(4) DEFAULT NULL COMMENT 'Kode area ',
  `vStPhoneNumber` varchar(20) DEFAULT NULL COMMENT 'No tlp yang bisa dihubungi ',
  `tCreated` datetime DEFAULT NULL COMMENT 'record tsb dibuat pd tgl',
  `cCreatedBy` char(7) DEFAULT NULL COMMENT 'record tsb dibuat oleh',
  `tUpdated` datetime DEFAULT NULL COMMENT 'record diupdate tgl',
  `cUpdatedBy` char(7) DEFAULT NULL COMMENT 'record diupdate oleh',
  `lDeleted` bit(1) NOT NULL COMMENT 'status delete',
  `dPrintSPK` date DEFAULT '0000-00-00' COMMENT 'tgl print SPK',
  `iBankTransfer` int(2) DEFAULT NULL,
  `dfired` date DEFAULT '0000-00-00' COMMENT 'tgl pemberhentian status karyawan',
  `drsreq` date DEFAULT '0000-00-00',
  `dresign` date DEFAULT '0000-00-00' COMMENT 'tgl pengunduran diri',
  `drightcal` date DEFAULT '0000-00-00',
  `dproses` date DEFAULT '0000-00-00' COMMENT 'tgl proses',
  `mreason` text COMMENT 'keterangan penyebab',
  `mphoto` text,
  `csex` char(1) DEFAULT NULL COMMENT 'jenis kelamin',
  `vhp` varchar(15) DEFAULT NULL COMMENT 'no hp',
  `vidrt` varchar(4) DEFAULT NULL COMMENT 'no RT tempat tinggal sesuai KTP',
  `vidrw` varchar(4) DEFAULT NULL COMMENT 'no RW tempat tinggal sesuai KTP',
  `iidprovid` int(2) DEFAULT NULL COMMENT 'id provinsi sesuai KTP',
  `vstrt` varchar(4) DEFAULT NULL COMMENT 'no RT tempat tinggal',
  `vstrw` varchar(4) DEFAULT NULL COMMENT 'no RW tempat tinggal',
  `vstblock` varchar(15) DEFAULT NULL COMMENT 'block tempat tinggal',
  `vstlot` varchar(3) DEFAULT NULL COMMENT 'lot. tempat tinggal',
  `vsthomeno` varchar(4) DEFAULT NULL COMMENT 'no rumah tempat tinggal',
  `istprovid` int(2) DEFAULT NULL COMMENT 'provinsi tempat tinggal',
  `vaccowner` varchar(30) DEFAULT NULL COMMENT 'account bank miliki',
  `dresignpayroll` date DEFAULT '0000-00-00' COMMENT 'catatan tgl resign disisi payroll',
  `lshift` bit(1) DEFAULT NULL,
  `lfood` bit(1) DEFAULT NULL,
  `cupperprev` char(7) DEFAULT NULL,
  `irefrid` int(1) DEFAULT NULL,
  `lhins` bit(1) DEFAULT NULL,
  `vhinsmemberno` varchar(15) DEFAULT NULL,
  `dhins` date DEFAULT '0000-00-00',
  `ihinsprovid` int(2) DEFAULT NULL,
  `iuppid` int(3) DEFAULT NULL,
  `igshiftid` int(2) DEFAULT NULL,
  `iPostIdPrev` int(3) DEFAULT NULL,
  `cNipold` char(7) DEFAULT NULL,
  `dprodem` date DEFAULT '0000-00-00',
  `cpending` varchar(100) DEFAULT NULL,
  `ipaystatus` int(2) DEFAULT NULL,
  `ctaxpayroll` char(2) DEFAULT NULL,
  `dNPWP` date DEFAULT '0000-00-00',
  `vPassword` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`cNip`),
  UNIQUE KEY `cNip` (`cNip`),
  KEY `FK_employee_Dept` (`iDeptID`),
  KEY `FK_employee_position` (`iPostID`),
  KEY `FK_employee_WorkStat` (`iWorkID`),
  KEY `cUpper` (`cUpper`),
  KEY `vNickName` (`vNickName`),
  KEY `dresign` (`dresign`),
  KEY `vName` (`vName`),
  KEY `IDX1` (`cNip`,`vName`),
  KEY `FK_employee_Company` (`iCompanyID`,`lDeleted`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC COMMENT='master informasi pegawai';

-- Membuang data untuk tabel erp_privi.employee: ~0 rows (lebih kurang)
DELETE FROM `employee`;
/*!40000 ALTER TABLE `employee` DISABLE KEYS */;
/*!40000 ALTER TABLE `employee` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
