 
<?php
/* Generated by Softdev 2 ERP Module Generator 2019-02-04 18:46:48 */
/* Location: ./modules/umum/controllers/mt03.php */
/* Please DO NOT modify this information : */ 


/*
    Preparation 
    1. untuk load view halaman upload , file berada pada folder partial;
    2. lib auth untuk fungsi check modul



    Parameter need to be change after generate 
    1. FOLDER_APP => change to folder name where this controllers should be there
    2. Static Dropdown => change value for option
    3. Dynamic Dropdown => Change query for option

    Table Sample 
    test.item && test.item_file_upload




*/
 


 
if ( ! defined('BASEPATH')) exit('No direct script access allowed');
class mt03 extends MX_Controller {
    function __construct() {
        parent::__construct();
        /*$this->dbset = $this->load->database('schedulercheck',false, true);*/
        $this->load->library('auth');
        $this->db = $this->load->database('hrd',false, true);
        $this->user = $this->auth->user();

       /* $checkMod = $this->auth->modul_set($this->input->get('modul_id'));
        $this->validation =$checkMod['iValidation'];*/

    }

    function index($action = '') {
        $action = $this->input->get('action');
        //Bikin Object Baru Nama nya $grid      
        $grid = new Grid;
        $grid->setTitle('MT03');
        $grid->setTable('bbpmsoh.mt03');      
        $grid->setUrl('mt03');

        //List Table
        $grid->addList('iMt01','iAda_batch','iTgl_expired','iEtiket_brosur','iM_jenis_brosur','iReq_permohonan','iPengantar_direktorat','iHasil_ppoh','iBahan_standard','iSubmit','iApprove','dApprove','cApprove','vRemark','vCatatan','cCreated','dCreated','cUpdated','dUpdated','lDeleted'); 
        $grid->setSortBy('iMt03');
        $grid->setSortOrder('DESC');  

        //List field
        $grid->addFields('iMt01','iAda_batch','iTgl_expired','iEtiket_brosur','iM_jenis_brosur','iReq_permohonan','iPengantar_direktorat','iHasil_ppoh','iBahan_standard','iSubmit','iApprove','dApprove','cApprove','vRemark','vCatatan','cCreated','dCreated','cUpdated','dUpdated','lDeleted'); 

        //Setting Grid Width Name 
        /*
        Kamu bisa merubah nama label dari sini, Contoh :
        $grid->setLabel('nama field','nama field yang akan diubah');

        */

        $grid->setWidth('iMt01', '100');
        $grid->setAlign('iMt01', 'left');
        $grid->setLabel('iMt01','No Request');
    
        $grid->setWidth('iAda_batch', '100');
        $grid->setAlign('iAda_batch', 'left');
        $grid->setLabel('iAda_batch','No Batch');
    
        $grid->setWidth('iTgl_expired', '100');
        $grid->setAlign('iTgl_expired', 'left');
        $grid->setLabel('iTgl_expired','Tanggal Kadaluarsa');
    
        $grid->setWidth('iEtiket_brosur', '100');
        $grid->setAlign('iEtiket_brosur', 'left');
        $grid->setLabel('iEtiket_brosur','iEtiket_brosur ');
    
        $grid->setWidth('iM_jenis_brosur', '100');
        $grid->setAlign('iM_jenis_brosur', 'left');
        $grid->setLabel('iM_jenis_brosur','Etiket ,Brosur ,Komposisi');
    
        $grid->setWidth('iReq_permohonan', '100');
        $grid->setAlign('iReq_permohonan', 'left');
        $grid->setLabel('iReq_permohonan','Permohonan Pengujian dari Perusahaan ybs');
    
        $grid->setWidth('iPengantar_direktorat', '100');
        $grid->setAlign('iPengantar_direktorat', 'left');
        $grid->setLabel('iPengantar_direktorat','Pengantar dari Direktorat Kesehatan Hewan');
    
        $grid->setWidth('iHasil_ppoh', '100');
        $grid->setAlign('iHasil_ppoh', 'left');
        $grid->setLabel('iHasil_ppoh','Hasil Rapat PPOH');
    
        $grid->setWidth('iBahan_standard', '100');
        $grid->setAlign('iBahan_standard', 'left');
        $grid->setLabel('iBahan_standard','iBahan_standard ');
    
        $grid->setWidth('iSubmit', '100');
        $grid->setAlign('iSubmit', 'left');
        $grid->setLabel('iSubmit','Status Submit');
    
        $grid->setWidth('iApprove', '100');
        $grid->setAlign('iApprove', 'left');
        $grid->setLabel('iApprove','Status Approval');
    
//Example modifikasi GRID ERP
    //- Set Query
        /*if ($this->validation) {
            $grid->setQuery('lDeleted = 0 ', null); 
        }*/

        

/*
    - Set Query
        $grid->setQuery('lDeleted = 0 ', null); 
        $grid->setQuery('plc2_upb.iupb_id IN (select distinct(bk.iupb_id) from plc2.plc2_upb_spesifikasi_fg bk where bk.iappqa=2 and bk.ldeleted=0)', null);  

    - Join Table
        $grid->setJoinTable('hrd.employee', 'employee.cNip = pk_master.vnip', 'inner');

    - Change Field Name
        $grid->changeFieldType('ideleted','combobox','',array(''=>'Pilih',0=>'Aktif',1=>'Tidak aktif'));
*/

    //set search
        $grid->setSearch('iMt01','iAda_batch','iTgl_expired','iEtiket_brosur','iM_jenis_brosur','iReq_permohonan','iPengantar_direktorat','iHasil_ppoh','iBahan_standard','iSubmit','iApprove','dApprove','cApprove','vRemark','vCatatan','cCreated','dCreated','cUpdated','dUpdated','lDeleted');
        
    //set required
        $grid->setRequired('iMt01','iAda_batch','iTgl_expired','iEtiket_brosur','iM_jenis_brosur','iReq_permohonan','iPengantar_direktorat','iHasil_ppoh','iBahan_standard','iSubmit','iApprove','dApprove','cApprove','vRemark','vCatatan','cCreated','dCreated','cUpdated','dUpdated','lDeleted'); 
        $grid->setGridView('grid');


        switch ($action) {
            case 'json':
                    $grid->getJsonData();
                    break;
            case 'view':
                    $grid->render_form($this->input->get('id'), true);
                    break;

             case 'create':
                    $grid->render_form();
                    break;
             
                case 'createproses':
                    echo $grid->saved_form();
                    break;
                  
           
            
            case 'update':
                    $grid->render_form($this->input->get('id'));
                    break;

        
            case 'updateproses':
                    echo $grid->updated_form();
                    break;
        
        
            case 'delete':
                    echo $grid->delete_row();
                    break; 
            /*
                //Ini Merupakan Standart Case Untuk Approve

                case 'approve':
                    echo $this->approve_view();
                    break;
                case 'approve_process':
                    echo $this->approve_process();
                    break;
                case 'reject':
                    echo $this->reject_view();
                    break;
                case 'reject_process':
                    echo $this->reject_process();
                    break;

                
            */ 
                case 'download':
                    $this->download($this->input->get('file'));
                    break;
            default:
                    $grid->render_grid();
                    break;
        }
    }



    //Jika Ingin Menambahkan Seting grid seperti button edit enable dalam kondisi tertentu
    /* 
    function listBox_Action($row, $actions) {
        if ($row->vNo_Or<>'' || $row->vNo_Or<>NULL) { 
                unset($actions['edit']);
        }
        return $actions;
    } 
    */

                        function insertBox_mt03_iMt01($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" />';
                            return $return;
                        }
                        
                        function updateBox_mt03_iMt01($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt03_iAda_batch($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" />';
                            return $return;
                        }
                        
                        function updateBox_mt03_iAda_batch($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt03_iTgl_expired($field, $id) {
                            $pilihan = array(0=>'--Pilih--',1=>'Satu', 2=>'Dua');
                            $return = '<select class="input_rows1 required" name="'.$field.'"  id="'.$id.'">';            
                            foreach($pilihan as $k=>$v) {
                                $return .= '<option value="'.$k.'">'.$v.'</option>';
                            }            
                            $return .= '</select>';

                        
                            return $return;
                        }
                        
                        function updateBox_mt03_iTgl_expired($field, $id, $value, $rowData) {
                            $pilihan = array(0=>'--Pilih--',1=>'Satu', 2=>'Dua');
                            if ($this->input->get('action') == 'view') {
                                $return = $pilihan[$value];
                            } else {
                                $return = '<select class="input_rows1 required" name="'.$field.'"  id="'.$id.'">';            
                                foreach($pilihan as $k=>$v) {
                                    if ($k == $value) $selected = ' selected';
                                    else $selected = '';
                                    $return .= '<option '.$selected.' value="'.$k.'">'.$v.'</option>';
                                }            
                                $return .= '</select>';
                            }
                                
                                
                            return $return;
                        }
                        
                        function insertBox_mt03_iEtiket_brosur($field, $id) {
                            $pilihan = array(0=>'--Pilih--',1=>'Satu', 2=>'Dua');
                            $return = '<select class="input_rows1 required" name="'.$field.'"  id="'.$id.'">';            
                            foreach($pilihan as $k=>$v) {
                                $return .= '<option value="'.$k.'">'.$v.'</option>';
                            }            
                            $return .= '</select>';

                        
                            return $return;
                        }
                        
                        function updateBox_mt03_iEtiket_brosur($field, $id, $value, $rowData) {
                            $pilihan = array(0=>'--Pilih--',1=>'Satu', 2=>'Dua');
                            if ($this->input->get('action') == 'view') {
                                $return = $pilihan[$value];
                            } else {
                                $return = '<select class="input_rows1 required" name="'.$field.'"  id="'.$id.'">';            
                                foreach($pilihan as $k=>$v) {
                                    if ($k == $value) $selected = ' selected';
                                    else $selected = '';
                                    $return .= '<option '.$selected.' value="'.$k.'">'.$v.'</option>';
                                }            
                                $return .= '</select>';
                            }
                                
                                
                            return $return;
                        }
                        
                        function insertBox_mt03_iM_jenis_brosur($field, $id) {
                            $pilihan = array(0=>'--Pilih--',1=>'Satu', 2=>'Dua');
                            $return = '<select class="input_rows1 required" name="'.$field.'"  id="'.$id.'">';            
                            foreach($pilihan as $k=>$v) {
                                $return .= '<option value="'.$k.'">'.$v.'</option>';
                            }            
                            $return .= '</select>';

                        
                            return $return;
                        }
                        
                        function updateBox_mt03_iM_jenis_brosur($field, $id, $value, $rowData) {
                            $pilihan = array(0=>'--Pilih--',1=>'Satu', 2=>'Dua');
                            if ($this->input->get('action') == 'view') {
                                $return = $pilihan[$value];
                            } else {
                                $return = '<select class="input_rows1 required" name="'.$field.'"  id="'.$id.'">';            
                                foreach($pilihan as $k=>$v) {
                                    if ($k == $value) $selected = ' selected';
                                    else $selected = '';
                                    $return .= '<option '.$selected.' value="'.$k.'">'.$v.'</option>';
                                }            
                                $return .= '</select>';
                            }
                                
                                
                            return $return;
                        }
                        
                        function insertBox_mt03_iReq_permohonan($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" />';
                            return $return;
                        }
                        
                        function updateBox_mt03_iReq_permohonan($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt03_iPengantar_direktorat($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" />';
                            return $return;
                        }
                        
                        function updateBox_mt03_iPengantar_direktorat($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt03_iHasil_ppoh($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" />';
                            return $return;
                        }
                        
                        function updateBox_mt03_iHasil_ppoh($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt03_iBahan_standard($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" />';
                            return $return;
                        }
                        
                        function updateBox_mt03_iBahan_standard($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt03_iSubmit($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" />';
                            return $return;
                        }
                        
                        function updateBox_mt03_iSubmit($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt03_iApprove($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" />';
                            return $return;
                        }
                        
                        function updateBox_mt03_iApprove($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
    /*
        //Ini Merupakan Standart Approve yang digunakan di erp
        function approve_view() {
            $echo = '<script type="text/javascript">
                         function submit_ajax(form_id) {
                            return $.ajax({
                                url: $("#"+form_id).attr("action"),
                                type: $("#"+form_id).attr("method"),
                                data: $("#"+form_id).serialize(),
                                success: function(data) {
                                    var o = $.parseJSON(data);
                                    var last_id = o.last_id;
                                    var url = "'.base_url().'processor/umum/mt03";                             
                                    if(o.status == true) { 
                                        $("#alert_dialog_form").dialog("close");
                                             $.get(url+"?action=update&id="+last_id, function(data) {
                                             $("div#form_mt03").html(data);
                                             
                                        });
                                        
                                    }
                                        reload_grid("grid_mt03");
                                }
                                
                             })
                         }
                     </script>';
            $echo .= '<h1>Approve</h1><br />';
            $echo .= '<form id="form_mt03_approve" action="'.base_url().'processor/umum/mt03?action=approve_process" method="post">';
            $echo .= '<div style="vertical-align: top;">';
            $echo .= 'Remark : 
                    <input type="hidden" name="iMt03" value="'.$this->input->get('iMt03').'" />
                    <input type="hidden" name="modul_id" value="'.$this->input->get('modul_id').'" />
                    <input type="hidden" name="lvl" value="'.$this->input->get('lvl').'" />
                    <input type="hidden" name="group_id" value="'.$this->input->get('group_id').'" />
                    
                    <textarea name="vRemark"></textarea>
            <button type="button" onclick="submit_ajax(\'form_mt03_approve\')">Approve</button>';
                
            $echo .= '</div>';
            $echo .= '</form>';
            return $echo;
        } 

        function approve_process() {
            $post = $this->input->post();
            $cNip= $this->user->gNIP;
            $vName= $this->user->gName;
            $iMt03 = $post['iMt03'];
            $vRemark = $post['vRemark'];
            $lvl = $post['lvl'];

            //Letakan Query Update approve disini

            $data['status']  = true;
            $data['last_id'] = $post['iMt03'];
            return json_encode($data);
        }
    */


    /*
        //Ini Merupakan Standart Reject yang digunakan di erp
        function reject_view() {
            $echo = '<script type="text/javascript">
                         function submit_ajax(form_id) {
                            var remark = $("#mt03_remark").val();
                            if (remark=="") {
                                alert("Remark tidak boleh kosong ");
                                return
                            }

                            return $.ajax({
                                url: $("#"+form_id).attr("action"),
                                type: $("#"+form_id).attr("method"),
                                data: $("#"+form_id).serialize(),
                                success: function(data) {
                                    var o = $.parseJSON(data);
                                    var last_id = o.last_id;
                                    var url = "'.base_url().'processor/umum/mt03";                             
                                    if(o.status == true) { 
                                        $("#alert_dialog_form").dialog("close");
                                             $.get(url+"?action=update&id="+last_id, function(data) {
                                             $("div#form_mt03").html(data);
                                             
                                        });
                                        
                                    }
                                        reload_grid("grid_mt03");
                                }
                                
                             })
                         }
                     </script>';
            $echo .= '<h1>Reject</h1><br />';
            $echo .= '<form id="form_mt03_reject" action="'.base_url().'processor/umum/mt03?action=reject_process" method="post">';
            $echo .= '<div style="vertical-align: top;">';
            $echo .= 'Remark : 
                    <input type="hidden" name="iMt03" value="'.$this->input->get('iMt03').'" />
                    <input type="hidden" name="modul_id" value="'.$this->input->get('modul_id').'" />
                    <input type="hidden" name="lvl" value="'.$this->input->get('lvl').'" />
                    <input type="hidden" name="group_id" value="'.$this->input->get('group_id').'" />
                    
                    <textarea name="vRemark" id="reject_mt03_remark"></textarea>
            <button type="button" onclick="submit_ajax(\'form_mt03_reject\')">Reject</button>';
                
            $echo .= '</div>';
            $echo .= '</form>';
            return $echo;
        }


        
        function reject_process() {
            $post = $this->input->post();
            $cNip= $this->user->gNIP;
            $vName= $this->user->gName;
            $iMt03 = $post['iMt03'];
            $vRemark = $post['vRemark'];
            $lvl = $post['lvl'];

            //Letakan Query Update approve disini

            $data['status']  = true;
            $data['last_id'] = $post['iMt03'];
            return json_encode($data);
        }
    */


    //Standart Setiap table harus memiliki dCreated , cCreated, dUpdated, cUpdated
    function before_insert_processor($row, $postData) {
        $postData['dCreated'] = date('Y-m-d H:i:s');
        $postData['cCreated']=$this->user->gNIP;


        if($postData['isdraft']==true){
            $postData['iSubmit']=0;
        } else{
            $postData['iSubmit']=1;
        } 


        return $postData;

    }
    function before_update_processor($row, $postData) {
        $postData['dUpdated'] = date('Y-m-d H:i:s');
        $postData['cUpdated'] = $this->user->gNIP;

        if($postData['isdraft']==true){
            $postData['iSubmit']=0;
        } else{
            $postData['iSubmit']=1;
        } 


        return $postData; 
    }    

    function after_insert_processor($fields, $id, $postData) {
        //Example After Insert
        /*
        $cNip = $this->sess_auth->gNIP; 
        $sql = 'Place Query In Here';
        $this->dbset->query($sql);
        */
    }

    function after_update_processor($fields, $id, $postData) {
        //Example After Update
        /*
        $cNip = $this->sess_auth->gNIP; 
        $sql = 'Place Query In Here';
        $this->dbset->query($sql);
        */
    }

    function manipulate_insert_button($buttons) { 
        //Load Javascript In Here 
        $cNip= $this->user->gNIP;
        $js = $this->load->view('js/standard_js');
        $js .= $this->load->view('js/upload_js');

        $iframe = '<iframe name="mt03_frame" id="mt03_frame" height="0" width="0"></iframe>';
        
        $save_draft = '<button onclick="javascript:save_draft_btn_multiupload(\'mt03\', \' '.base_url().'processor/folder_app/mt03?draft=true \',this,true )"  id="button_save_draft_mt03"  class="ui-button-text icon-save" >Save as Draft</button>';
        $save = '<button onclick="javascript:save_btn_multiupload(\'mt03\', \' '.base_url().'processor/folder_app/mt03?company_id='.$this->input->get('company_id').'&group_id='.$this->input->get('group_id').'modul_id='.$this->input->get('modul_id').' \',this,true )"  id="button_save_submit_mt03"  class="ui-button-text icon-save" >Save &amp; Submit</button>';

        

        $buttons['save'] = $iframe.$save_draft.$save.$js;
        
        return $buttons;
    }

    function manipulate_update_button($buttons, $rowData) { 
        $peka=$rowData['iMt03'];


        //Load Javascript In Here 
        $cNip= $this->user->gNIP;
        $js = $this->load->view('js/standard_js');
        $js .= $this->load->view('js/upload_js');

        $iframe = '<iframe name="mt03_frame" id="mt03_frame" height="0" width="0"></iframe>';
        
        $update_draft = '<button onclick="javascript:update_draft_btn(\'mt03\', \' '.base_url().'processor/folder_app/mt03?draft=true \',this,true )"  id="button_update_draft_mt03"  class="ui-button-text icon-save" >Update as Draft</button>';
        $update = '<button onclick="javascript:update_btn_back(\'mt03\', \' '.base_url().'processor/folder_app/mt03?company_id='.$this->input->get('company_id').'&group_id='.$this->input->get('group_id').'modul_id='.$this->input->get('modul_id').' \',this,true )"  id="button_update_submit_mt03"  class="ui-button-text icon-save" >Update &amp; Submit</button>';

        $approve = '<button onclick="javascript:load_popup(\' '.base_url().'processor/folder_app/mt03?action=approve&iMt03='.$peka.'&company_id='.$this->input->get('company_id').'&group_id='.$this->input->get('group_id').'&modul_id='.$this->input->get('modul_id').' \')"  id="button_approve_mt03"  class="ui-button-text icon-save" >Approve</button>';
        $reject = '<button onclick="javascript:load_popup(\' '.base_url().'processor/folder_app/mt03?action=reject&iMt03='.$peka.'&company_id='.$this->input->get('company_id').'&group_id='.$this->input->get('group_id').'&modul_id='.$this->input->get('modul_id').' \' )"  id="button_reject_mt03"  class="ui-button-text icon-save" >Reject</button>';
        



        if ($this->input->get('action') == 'view') {
            unset($buttons['update']);
        }
        else{ 
            $buttons['update'] = $iframe.$update_draft.$update.$js;    
        }
        
        return $buttons;
    }

    function whoAmI($nip) { 
        $sql = 'select b.vDescription as vdepartemen,a.*,b.*,c.iLvlemp 
                        from hrd.employee a 
                        join hrd.msdepartement b on b.iDeptID=a.iDepartementID
                        join hrd.position c on c.iPostId=a.iPostID
                        where a.cNip ="'.$nip.'"
                        ';
        
        $data = $this->dbset->query($sql)->row_array();
        return $data;
    }

    function download($vFilename) { 
        $this->load->helper('download');        
        $name = $vFilename;
        $id = $_GET['id'];
        $tempat = $_GET['path'];    
        $path = file_get_contents('./files/folder_app/'.$tempat.'/'.$id.'/'.$name);    
        force_download($name, $path);


    }

    //Output
    public function output(){
        $this->index($this->input->get('action'));
    }

}
