 
        <?php
        /* Generated by Sovdev 2 ERP CRUD Generator 2018-08-15 14:01:50 */
        /* Location: ./modules/schedulercheck/controllers/aplikasi_monitoring_erp.php */
        /* Please DO NOT modify this information : */ 
         
        if ( ! defined('BASEPATH')) exit('No direct script access allowed');
        class aplikasi_monitoring_erp extends MX_Controller {
            function __construct() {
                parent::__construct();
$this->db_schedulercheck = $this->load->database('schedulercheck',false, true);
                $this->load->library('auth');
                $this->db = $this->load->database('hrd', true);
                $this->user = $this->auth->user();
            }
            function index($action = '') {
                $action = $this->input->get('action');
                //Bikin Object Baru Nama nya $grid      
                $grid = new Grid;
                $grid->setTitle('Version Monitoring');
                $grid->setTable('hrd.svn_info');      
                $grid->setUrl('aplikasi_monitoring_erp');

                //List Table
                $grid->addList('vName','vDescription','eType','vURL'); 
                $grid->setSortBy('iSvnId');
                $grid->setSortOrder('asc');  

                //List field
                $grid->addFields('vName','vDescription','eType','vURL','ctags'); 

                //Setting Grid Width Name 
                /*
                    Kamu bisa merubah nama label dari sini, Contoh :
                    $grid->setLabel('nama field','nama field yang akan diubah');

                */
        
                $grid->setWidth('vName', '250');
                $grid->setAlign('vName', 'left');
                $grid->setLabel('vName','Inisial');
            
                $grid->setWidth('eType', '100');
                $grid->setAlign('eType', 'left');
                $grid->setLabel('eType','Type');
            
                $grid->setWidth('vURL', '300');
                $grid->setAlign('vURL', 'left');
                $grid->setLabel('vURL','URL');
            
                $grid->setWidth('vDescription', '250');
                $grid->setAlign('vDescription', 'left');
                $grid->setLabel('vDescription','Aplikasi');

                $grid->setWidth('ctags', '200');
                $grid->setAlign('ctags', 'left');
                $grid->setLabel('ctags','Version Info');

                
             
                //Example modifikasi GRID ERP
                /*
                    - Set Query
                        $grid->setQuery('lDeleted = 0 ', null); 
                        $grid->setQuery('plc2_upb.iupb_id IN (select distinct(bk.iupb_id) from plc2.plc2_upb_spesifikasi_fg bk where bk.iappqa=2 and bk.ldeleted=0)', null);  

                    - Join Table
                        $grid->setJoinTable('hrd.employee', 'employee.cNip = pk_master.vnip', 'inner');

                    - Change Field Name
                        $grid->changeFieldType('ideleted','combobox','',array(''=>'Pilih',0=>'Aktif',1=>'Tidak aktif'));
                */

                 //set search
                $grid->setSearch('vName','eType');
                 

                $grid->setGridView('grid');

                switch ($action) {
                    case 'json':
                            $grid->getJsonData();
                            break;
                    case 'view':
                            $grid->render_form($this->input->get('id'), true);
                            break;
                    case 'create':
                            $grid->render_form();
                            break;
                    case 'createproses':
                            echo $grid->saved_form();
                            break;
                    case 'update':
                            $grid->render_form($this->input->get('id'));
                            break;
                    case 'updateproses':
                            echo $grid->updated_form();
                            break;
                    case 'delete':
                            echo $grid->delete_row();
                            break; 
                    /*
                        //Ini Merupakan Standart Case Untuk Approve

                        case 'approve':
                            echo $this->approve_view();
                            break;
                        case 'approve_process':
                            echo $this->approve_process();
                            break;
                        case 'reject':
                            echo $this->reject_view();
                            break;
                        case 'reject_process':
                            echo $this->reject_process();
                            break; 
                    */ 
                    default:
                            $grid->render_grid();
                            break;
                }
            }
            //Create Manipulate Field 

            //Jika Ingin Menambahkan Seting grid seperti button edit enable dalam kondisi tertentu
            /* 
            function listBox_Action($row, $actions) {
                if ($row->vNo_Or<>'' || $row->vNo_Or<>NULL) { 
                        unset($actions['edit']);
                }
                return $actions;
            } 
            */
        
            function insertBox_aplikasi_monitoring_erp_vName($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';
                return $return;
            }
            function updateBox_aplikasi_monitoring_erp_vName($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50"  value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 50) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';

                } 
                return $return;
            }   
            
            function insertBox_aplikasi_monitoring_erp_eType($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                return $return;
            }
            function updateBox_aplikasi_monitoring_erp_eType($field, $id, $value, $rowData) {
                    if ($this->input->get('action') == 'view') {
                        $return= $value; 
                    }
                    else{
                        $return = '<input type="text" name="'.$field.'"  id="'.$id.'" value="'.$value.'" class="input_rows1 required" size="30" />';
                    } 
                return $return;
            }   
            
            function insertBox_aplikasi_monitoring_erp_vURL($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "160" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 160);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(160 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">160</span> karakter<br/>';
                return $return;
            }
            function updateBox_aplikasi_monitoring_erp_vURL($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "160"  value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 160) {
                                            this.value = this.value.substring(0, 160);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(160 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">160</span> karakter<br/>';

                } 
                return $return;
            }   
            
            function insertBox_aplikasi_monitoring_erp_vDescription($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "160" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 160);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(160 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">160</span> karakter<br/>';
                return $return;
            }
            function updateBox_aplikasi_monitoring_erp_vDescription($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "160"  value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 160) {
                                            this.value = this.value.substring(0, 160);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(160 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">160</span> karakter<br/>';

                } 
                return $return;
            }   
            
            function insertBox_aplikasi_monitoring_erp_ctags($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                return $return;
            }
            function updateBox_aplikasi_monitoring_erp_ctags($field, $id, $value, $rowData) {
                    $getEnd = end(explode('/',$rowData['vURL']));
                    if ($getEnd == 'tags') {
                        $tags = '';
                    }else if ($getEnd == 'trunk'){
                        $tags = '';
                    }else{
                        $tags = '/tags';
                    }

                    $cmd = "svn log -v --username machine --password irobot  ".$rowData['vURL'].$tags." | awk '/^ *A/ { print $2 }' | grep -v RC | head -1"; 
                    exec($cmd, $output, $return_var); 
                    $v = $output[0];  
                    unset($output); 
                    $return = '<b>'.$v.'</b>';   
                    return $return;
            }   
            
            function insertBox_aplikasi_monitoring_erp_tUpdated($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                return $return;
            }
            function updateBox_aplikasi_monitoring_erp_tUpdated($field, $id, $value, $rowData) {
                    if ($this->input->get('action') == 'view') {
                        $return= $value; 
                    }
                    else{
                        $return = '<input type="text" name="'.$field.'"  id="'.$id.'" value="'.$value.'" class="input_rows1 required" size="30" />';
                    } 
                return $return;
            }   
            
            function insertBox_aplikasi_monitoring_erp_tLastLoadSvn($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" />';
                $return .= '<script>
                                $("#'.$id.'").datepicker({  changeMonth:true,
                                        changeYear:true,
                                        dateFormat:"yy-mm-dd"}); 
                             </script>';
                return $return;
            }
            function updateBox_aplikasi_monitoring_erp_tLastLoadSvn($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").datepicker({
                                    changeMonth:true,
                                    changeYear:true,
                                    dateFormat:"yy-mm-dd"
                                });
                             </script>';
                } 
                return $return;
            }   
            
            /*
                //Ini Merupakan Standart Approve yang digunakan di erp
 
                function approve_view() {
                    $echo = '<script type="text/javascript">
                                 function submit_ajax(form_id) {
                                    return $.ajax({
                                        url: $("#"+form_id).attr("action"),
                                        type: $("#"+form_id).attr("method"),
                                        data: $("#"+form_id).serialize(),
                                        success: function(data) {
                                            var o = $.parseJSON(data);
                                            var last_id = o.last_id;
                                            var url = "'.base_url().'processor/schedulercheck/aplikasi_monitoring_erp";                             
                                            if(o.status == true) { 
                                                $("#alert_dialog_form").dialog("close");
                                                     $.get(url+"?action=update&id="+last_id, function(data) {
                                                     $("div#form_aplikasi_monitoring_erp").html(data);
                                                     
                                                });
                                                
                                            }
                                                reload_grid("grid_aplikasi_monitoring_erp");
                                        }
                                        
                                     })
                                 }
                             </script>';
                    $echo .= '<h1>Approve</h1><br />';
                    $echo .= '<form id="form_aplikasi_monitoring_erp_approve" action="'.base_url().'processor/schedulercheck/aplikasi_monitoring_erp?action=approve_process" method="post">';
                    $echo .= '<div style="vertical-align: top;">';
                    $echo .= 'Remark : 
                            <input type="hidden" name="iSvnId" value="'.$this->input->get('iSvnId').'" />
                            <input type="hidden" name="lvl" value="'.$this->input->get('lvl').'" />
                            <input type="hidden" name="group_id" value="'.$this->input->get('group_id').'" />
                            <input type="hidden" name="modul_id" value="'.$this->input->get('modul_id').'" />
                            <textarea name="vRemark"></textarea>
                    <button type="button" onclick="submit_ajax(\'form_aplikasi_monitoring_erp_approve\')">Approve</button>';
                        
                    $echo .= '</div>';
                    $echo .= '</form>';
                    return $echo;
                } 
 
                function approve_process() {
                    $post = $this->input->post();
                    $cNip= $this->user->gNIP;
                    $vName= $this->user->gName;
                    $iSvnId = $post['iSvnId'];
                    $vRemark = $post['vRemark'];
                    $lvl = $post['lvl'];
 
                    //Letakan Query Update approve disini

                    $data['status']  = true;
                    $data['last_id'] = $post['iSvnId'];
                    return json_encode($data);
                }
            */

        
            /*
                //Ini Merupakan Standart Reject yang digunakan di erp

                function reject_view() {
                    $echo = '<script type="text/javascript">
                                 function submit_ajax(form_id) {
                                    var remark = $("#aplikasi_monitoring_erp_remark").val();
                                    if (remark=="") {
                                        alert("Remark tidak boleh kosong ");
                                        return
                                    }

                                    return $.ajax({
                                        url: $("#"+form_id).attr("action"),
                                        type: $("#"+form_id).attr("method"),
                                        data: $("#"+form_id).serialize(),
                                        success: function(data) {
                                            var o = $.parseJSON(data);
                                            var last_id = o.last_id;
                                            var url = "'.base_url().'processor/schedulercheck/aplikasi_monitoring_erp";                             
                                            if(o.status == true) { 
                                                $("#alert_dialog_form").dialog("close");
                                                     $.get(url+"?action=update&id="+last_id, function(data) {
                                                     $("div#form_aplikasi_monitoring_erp").html(data);
                                                     
                                                });
                                                
                                            }
                                                reload_grid("grid_aplikasi_monitoring_erp");
                                        }
                                        
                                     })
                                 }
                             </script>';
                    $echo .= '<h1>Reject</h1><br />';
                    $echo .= '<form id="form_aplikasi_monitoring_erp_reject" action="'.base_url().'processor/schedulercheck/aplikasi_monitoring_erp?action=reject_process" method="post">';
                    $echo .= '<div style="vertical-align: top;">';
                    $echo .= 'Remark : 
                            <input type="hidden" name="iSvnId" value="'.$this->input->get('iSvnId').'" />
                            <input type="hidden" name="lvl" value="'.$this->input->get('lvl').'" />
                            <input type="hidden" name="group_id" value="'.$this->input->get('group_id').'" />
                            <input type="hidden" name="modul_id" value="'.$this->input->get('modul_id').'" />
                            <textarea name="vRemark" id="reject_aplikasi_monitoring_erp_remark"></textarea>
                    <button type="button" onclick="submit_ajax(\'form_aplikasi_monitoring_erp_reject\')">Reject</button>';
                        
                    $echo .= '</div>';
                    $echo .= '</form>';
                    return $echo;
                }


                
                function reject_process() {
                    $post = $this->input->post();
                    $cNip= $this->user->gNIP;
                    $vName= $this->user->gName;
                    $iSvnId = $post['iSvnId'];
                    $vRemark = $post['vRemark'];
                    $lvl = $post['lvl'];
 
                    //Letakan Query Update approve disini

                    $data['status']  = true;
                    $data['last_id'] = $post['iSvnId'];
                    return json_encode($data);
                }
            */

        
            //Standart Setiap table harus memiliki dCreate , cCreated, dupdate, cUpdate
            function before_insert_processor($row, $postData) {
                $postData['dCreate'] = date('Y-m-d H:i:s');
                $postData['cCreated']=$this->user->gNIP;
                return $postData;

            }
            function before_update_processor($row, $postData) {
                $postData['dupdate'] = date('Y-m-d H:i:s');
                $postData['cUpdate'] = $this->user->gNIP;
                return $postData; 
            }    
        
            function after_insert_processor($fields, $id, $postData) {
                //Example After Insert
                /*
                $cNip = $this->sess_auth->gNIP; 
                $sql = 'Place Query In Here';
                $this->db_schedulercheck->query($sql);
                */
            }
    
            function after_update_processor($fields, $id, $postData) {
                //Example After Update
                /*
                $cNip = $this->sess_auth->gNIP; 
                $sql = 'Place Query In Here';
                $this->db_schedulercheck->query($sql);
                */
            }
            function manipulate_update_button($buttons, $rowData) { 
                //Load Javascript In Here 
                if ($this->input->get('action') == 'view') {
                    unset($buttons['update']);
                }
                else{ 
                    
                }
                
                return $buttons;
            }
            //Output
            public function output(){
                $this->index($this->input->get('action'));
            }
        }