 
        <?php
        ini_set('max_execution_time', 300);
        /* Generated by Sovdev 2 ERP CRUD Generator 2017-09-18 10:31:46 */
        /* Location: ./modules/schedulercheck/controllers/pamsh_nvl.php */
        /* Please DO NOT modify this information : */ 
         
        /*------------------------------------------------------Instuction------------------------------------------------------*/
        /*
         hal hal yang perlu diperhatikan untuk diganti variablenya adalah sbb:
              $selectCompany='3'; 
         1. koneksi mysql
               $host = '10.1.49.8';
               $user = 'nplnet';
               $pass = 'nplnet01';
               $db='purchase';


         2. ODBC Connection 
               $conn=odbc_connect('debef','','');

         3. Parameter 
               - $scheduler_name='pamsh_nvl';
               - $BackdateI='1';
               - $tbsql='purchase.pamsh';
               - $pk=odbc_result($rs,'C_PANUMB');
               - $fPk='C_FACCODE';
               - $pkv=odbc_result($rs,'C_PANUMB').' - '.odbc_result($rs,'C_PANUMB');
               - $tbsch = 'plc2.scheduler_score';
               - $dbFile='pamsh';
               - $dbfFile = realpath('//10.1.48.21/Sys2/DATA/PURCHASE/pamsh.dbf');
               - $sql='SELECT * FROM  where d_lastupdt BETWEEN #$tgl1# AND #$tgl2#';


         4. Refference 
            - https://www.connectionstrings.com/dbf-foxpro/
            - https://www.pcreview.co.uk/threads/import-dbf-files-with-memo-fields.2651051/
            - http://php.net/manual/en/function.odbc-exec.php

      */

        /*------------------------------------------------------Instuction------------------------------------------------------*/
            ini_set('max_execution_time', 300);    
            error_reporting(E_ALL);
            ini_set('display_errors', '1');

         
           /*-----------------------------------------------------Mysql Connection Start------------------------------------------------------*/
              //  $host = '10.1.49.8';
              //  $user = 'nplnet';
              //  $pass = 'nplnet01';
              //  $db='purchase';

              // $conn = mysql_connect($host, $user, $pass);
              // if ($conn) {
              //     mysql_select_db($db, $conn);
              // } else {
              //    die('Error : '.mysql_error());
              // }
              include('koneksi.php');
           /*------------------------------------------------------Mysql Connection End------------------------------------------------------*/

         
             /*-----------------------------------------------------ODBC Connection Start-----------------------------------------------------*/

            $dbfFile = realpath('G:/ETERCON/DATA/PURCHASE/pamsh.dbf');
            $dbfDir = dirname($dbfFile);
            $dbfDir1 = 'G:/ETERCON/DATA/PURCHASE';
            $conn = odbc_connect('Driver={Microsoft Visual FoxPro Driver};SourceType=DBF;SourceDB='.$dbfDir1.';Exclusive=No;Collate=Machine;NULL=NO;DELETED=YES;BACKGROUNDFETCH=NO;' , '', '');
         
            //=odbc_connect('vfpDriver','','');
             if (!$conn)
             {
                exit('Connection Failed: ' . $conn);
             }else{
                //echo 'Connected';
                //exit;
             }  
            /*------------------------------------------------------ODBC Connection End------------------------------------------------------*/
         
          /*------------------------------------------------------Parameter Start------------------------------------------------------*/
              $selectCompany='5'; 
              $scheduler_name='mbr_etc';

              /*number of days back from now */
              $BackdateI='1';
              $last_update='D_LASTUPDT';

              
              $tgl2 = date('Ymd');
              $backback = strtotime('- '.$BackdateI.' days', strtotime($tgl2));
              $tgl1 = date('Ymd', $backback);

              /*Setting Table Destination*/
              $tbsql='kanban.kbn_mbr';

              $dbFile='pamsh';

              

              /*flag finish running*/
              $isFinish = false;


           /*------------------------------------------------------Parameter End------------------------------------------------------*/
         
                /* Select data from DBF*/
                /*parsing parameter with hastag (#) */
                 //$sql='SELECT * FROM '.$dbFile.' where d_lastupdt BETWEEN #$tgl1# AND #$tgl2#';

                 

               if($last_update<>'-'){
                  $sql = 'SELECT * From '.$dbFile.'  WHERE DTOS('.$dbFile.'.'.$last_update.') BETWEEN "'.$tgl1.'"  and "'.$tgl2.'" ';
                }else{
                  $sql='SELECT * FROM '.$dbFile.' ';
                }


                 
                 //echo ;
                 //exit;
             
                $rs=odbc_exec($conn,$sql);

                if (!$rs)
                 {
                    exit('ODBC Exec failed: ' . $sql);
                 }else{
                    //echo 'Success Query';
                    //exit;
                 }  


                 /*Get Field Name*/
                 $arrNmKolom = array();
                 
                 for($i=1; $i <= odbc_num_fields($rs); $i++){
                  /*push field name to array*/
                  array_push($arrNmKolom,odbc_field_name($rs, $i) );

                 }

                 

         
                /*------------------------------------------------Processing Data Start------------------------------------------------------*/
                //function processingData(){
                 if (!$rs)
                 {
                    exit('Error in SQL');
                 }

                 // $html used to show data
                 $html  ='';
                 $html .= '<table>';
                 $html .= '<tr>';
                 for($i=1; $i <= odbc_num_fields($rs); $i++){
                    $html .= '<th>'.odbc_field_name($rs, $i).'</th>'; 
                 

                 }
                 $html .= '</tr>';

                 
                 $arriSi= array();
                 //echo "atas";
                while (odbc_fetch_row($rs))
                {
                    echo trim(odbc_result($rs,'c_panumb1'));
                    echo "<br>";
                    /*describe PK Column & get Value of PK*/
                    $pk=odbc_result($rs,'c_panumb');
                    $fPk='vPa_no';

                    /*describe PK show when transfering*/
                    //$pkv= $pk;
                    $pkv=trim(odbc_result($rs,'c_panumb1')).' - '.odbc_result($rs,'c_panumb');
                   
                    /*cek data existing in mysql table*/
                    /*param use here*/

                    $sqlUdah = 'select * from kanban.kbn_mbr a where a.vPa_no= "'.$pk.'" and  iCompany = "'.$selectCompany.'" ' ;
                    //echo "cek udah ".$sqlUdah;
                    //exit;
                    $rowUdah = mysql_fetch_array(mysql_query($sqlUdah));

                    if (!empty($rowUdah)) 
                    {
                      // updating record when exists
                      $sa = '';
                      echo 'Updating ... '.$pkv;
                      
                     
                      $sa.='UPDATE '.$tbsql.' SET ';
                      $i=0;
                      
                      $flg = trim(odbc_result($rs,'c_flgprd'));
                      if($flg==''){
                        $flg = 'Null';
                      }else{
                        $flg = "'".$flg."'";
                      }

                      $stt = trim(odbc_result($rs,'c_status'));

                      if($stt==''){
                        $stt = 'Null';
                      }else{
                        $stt = "'".$stt."'";
                      }

                      $lok = trim(odbc_result($rs,'c_lokasi'));
                      if($lok==''){
                        $lok = 'Null';
                      }else{
                        $lok = "'".$lok."'";
                      }


                      $sa.= "cFlgPrd= ".$flg;  
                      $sa.= ",cStatus=".$stt;    
                      $sa.= ",c_lokasi=".$lok;    
                      
                      
                
                      $sa.=' where  '.$fPk.'  = "'.$pk.'" and  iCompany = "'.$selectCompany.'"    ';
                        //echo $sa;
                        echo '<br>';

                        if(!mysql_query($sa)){
                            echo $sa;
                            $isFinish = false;
                            schLogger($scheduler_name,$isFinish,mysql_error(),$sa);
                            die('Mysql Failed 2 - '.mysql_error());
                        }
                            else {echo 'Transfering ...'.$pkv.'-'.$scheduler_name.' <br>';
                        }
                    }else{
                        $sa = '';
                        $sqlit =  'select * from sales.itemas a where a.c_iteno = "'.odbc_result($rs,'c_iteno').'" ' ;
                        $resultE = mysql_query($sqlit);
                        $row = mysql_fetch_array($resultE);

                      

                       echo 'Inserting ... '.$pkv;
                       $sa .='INSERT INTO '.$tbsql.'(vBatch_no,vPa_no,vKode_obat,vNama,vJenis_obat,iQty,dTanggal_mbr,iCompany,c_lokasi';
                       $sa.=')VALUES(';
                        $sa.= "'".trim(odbc_result($rs,'c_panumb1'))."'";
                        $sa.=",'".odbc_result($rs,'c_panumb')."'";
                        $sa.=",'".odbc_result($rs,'c_iteno')."'";

                        $sa.=",'".trim($row['c_itnam'])."'";
                        $sa.=",'".$row['c_jenis']."'";

                        $sa.=",'".odbc_result($rs,'n_batsize')."'";
                        $sa.=",'".odbc_result($rs,'d_plandate')."'";
                        $sa.=",".$selectCompany;
                        $sa.=",'".odbc_result($rs,'c_lokasi')."'";
                        $sa.=');';
                        //echo '<pre>'.$sa;
                        echo '<br>';
                       if(!mysql_query($sa)){
                          echo '<pre>Error - '.$sa;

                          /*$isFinish = false;
                          schLogger($scheduler_name,$isFinish,mysql_error(),$sa);*/
                          die('Mysql Failed 3 - '.mysql_error());
                       }
                          else {echo 'Transfering ...'.$pkv.'-'.$scheduler_name.' <br>';
                       }



                    }
                }
                //echo "bawah";
                $html .= '</table>';
                $html .= '<br>';
         
                 /* Finish Processing Data*/
                 $isFinish = true;
                 schLogger($scheduler_name,$isFinish,'done','Everything is OK');

                 /*close odbc Connection*/
                 odbc_close($conn);
              //}
                
           /*------------------------------------------------------Processing Data End------------------------------------------------------*/
        

                function schLogger($sched,$res,$notes,$warning){
                  /*Setting Table score*/
                  $tbsch = 'plc2.scheduler_score';

                  $now = date('Y-m-d H:i:s');
                  $cType = 'php';
                  if($res===True){
                     $iStatus = 1;
                  }else{
                     $iStatus = 0;
                  }

                  $sql ='INSERT INTO '.$tbsch.'(vScheduler_Name, cType,dDateRunning,iStatus,dCreate,vErrorLogs ) 
                           VALUES("'. $sched .'",
                                    "'. $cType .'",
                                    "'. $now .'",
                                    "'. $iStatus .'",
                                    "'. $now .'",
                                    "'. $notes .'"
                                    )';

                  if(!mysql_query($sql)){
                     echo $sql;
                     die('Mysql Failed 4 - '.mysql_error());
                  }
                     else {echo 'Logging ...<br>';
                  }


               }


                function get_type($type='V'){
                  switch ($type) {
                     case 'C': //Varchar
                     case 'c': //Varchar
                        $re['jenis']='varchar';
                        $re['fld']='(255)';
                        break;
                     case 'D': //Varchar
                     case 'd': //Varchar
                        $re['jenis']='date';
                        $re['fld']='';
                        break;
                     case 'N': // Number
                     case 'n': // Number
                     case 'L': // Bit
                     case 'l': // Bit
                        $re['jenis']='int';
                        $re['fld']='(11)';
                        break;
                     
                     default:
                        $re['jenis']='varchar';
                        $re['fld']='(255)';
                        break;
                  }

                  return $re;

                }    

                    
             