 
        <?php
        /* Generated by Sovdev 2 ERP CRUD Generator 2017-09-18 10:31:46 */
        /* Location: ./modules/schedulercheck/controllers/pamsh_nvl.php */
        /* Please DO NOT modify this information : */ 
         
        /*------------------------------------------------------Instuction------------------------------------------------------*/
        /*
         hal hal yang perlu diperhatikan untuk diganti variablenya adalah sbb:
              $selectCompany='3'; 
         1. koneksi mysql
               $host = '10.1.49.8';
               $user = 'nplnet';
               $pass = 'nplnet01';
               $db='purchase';


         2. ODBC Connection 
               $conn=odbc_connect('debef','','');

         3. Parameter 
               - $scheduler_name='pamsh_nvl';
               - $BackdateI='1';
               - $tbsql='purchase.pamsh';
               - $pk=odbc_result($rs,'C_PANUMB');
               - $fPk='C_FACCODE';
               - $pkv=odbc_result($rs,'C_PANUMB').' - '.odbc_result($rs,'C_PANUMB');
               - $tbsch = 'plc2.scheduler_score';
               - $dbFile='pamsh';
               - $dbfFile = realpath('//10.1.48.21/Sys2/DATA/PURCHASE/pamsh.dbf');
               - $sql='SELECT * FROM  where d_lastupdt BETWEEN #$tgl1# AND #$tgl2#';


         4. Refference 
            - https://www.connectionstrings.com/dbf-foxpro/
            - https://www.pcreview.co.uk/threads/import-dbf-files-with-memo-fields.2651051/
            - http://php.net/manual/en/function.odbc-exec.php

      */

        /*------------------------------------------------------Instuction------------------------------------------------------*/
         
            error_reporting(E_ALL);
            ini_set('display_errors', '1');

         
           /*-----------------------------------------------------Mysql Connection Start------------------------------------------------------*/
              //  $host = '10.1.49.8';
              //  $user = 'nplnet';
              //  $pass = 'nplnet01';
              //  $db='purchase';

              // $conn = mysql_connect($host, $user, $pass);
              // if ($conn) {
              //     mysql_select_db($db, $conn);
              // } else {
              //    die('Error : '.mysql_error());
              // }
              include('koneksi.php');
           /*------------------------------------------------------Mysql Connection End------------------------------------------------------*/

         
             /*-----------------------------------------------------ODBC Connection Start-----------------------------------------------------*/

              //  dir puchase
                  $dbPamsh='pamsh';
                  $dbfDirPurch = 'G:/DATA/PURCHASE';
                  $connPurch = odbc_connect('Driver={Microsoft Visual FoxPro Driver};SourceType=DBF;SourceDB='.$dbfDirPurch.';Exclusive=No;Collate=Machine;NULL=NO;DELETED=YES;BACKGROUNDFETCH=NO;' , '', '');
                  

                  if (!$connPurch){
                      exit('Connection Failed: ' . $connPurch);
                  }

                  
                  
                  
                  
         
            
             
            /*------------------------------------------------------ODBC Connection End------------------------------------------------------*/
         
          /*------------------------------------------------------Parameter Start------------------------------------------------------*/
            $paNumber = '16013096';
            $year = 2000+substr($paNumber, 0,2);

            
           /*------------------------------------------------------Parameter End------------------------------------------------------*/
              
              $dbfDirUmum = 'G:/DATA/UMUM';

              $dbfDirUmumPa = 'G:/DATA/UMUM'.'/mbr/'.$year.'/'.$paNumber.'/';

              $connUmum = odbc_connect('Driver={Microsoft Visual FoxPro Driver};SourceType=DBF;SourceDB='.$dbfDirUmum.';Exclusive=No;Collate=Machine;NULL=NO;DELETED=YES;BACKGROUNDFETCH=NO;' , '', '');            

              if (!$connUmum){
                      exit('Connection Failed: ' . $connUmum);
              }else{
                    echo $dbfDirUmumPa;
                    $dbFile='batpacka';
                    $sqlUmum ='SELECT * FROM '.$dbFile.' ';
                    echo $sqlUmum;
                    $rsUmum=odbc_exec($connUmum,$sqlUmum);

                    if (!$rsUmum)
                     {
                        exit('ODBC Exec failed: ' . $sqlUmum);
                     }else{
                        echo 'Ada di folder';
                        exit;
                     }  

              }

             


              //$lcumum = gcdirumum+'\mbr\'+lcpanumb';

          /*function */
              function bukaTabel(){


              }

              exit;

          /*function*/

                
             