<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
class scheduler_generator extends MX_Controller {
    function __construct() {
        parent::__construct();
        $this->db = $this->load->database('hrd',false, true);
        $this->load->library('auth');
        $this->dbset = $this->load->database('hrd', true);
        $this->user = $this->auth->user();
    }
    function index($action = '') {
        $action = $this->input->get('action') ? $this->input->get('action') : 'piew';   
        $grid = new Grid;
        $grid->setTitle('CRUD Master'); 
        $grid->setTable('hrd.scheduler_group_pic');     
        $grid->setUrl('scheduler_generator'); 
        
        switch ($action) {
                case 'piew': 
                        $data = array(
                            'url'=>base_url().'processor/schedulercheck/scheduler_generator?action=write',
                            'url2'=>base_url().'processor/schedulercheck/scheduler_generator?action=addTable',
                            'db' => $this->db->query('SHOW DATABASES')->result_array(),
                            'modules' =>  scandir('modules',1),
                        );
                        $this->load->view('generator_scheduler/create_dashboard',$data); 
                        break;
                case 'write':
                        $this->write();
                        break;
                case 'addTable':
                        $this->addTable();
                        break;
                default:
                        $grid->render_grid();
                        break;
        }
    }
    function addTable(){
        $nameDB = $this->input->post('nameDB');
        $tables = "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE `TABLE_SCHEMA` ='".$nameDB."'"; 
        $load_tb = $this->db->query($tables)->result_array();

        echo '<select id="openTable" class="openTable" name="openTable">';
        echo '<option value="">-Select Table-</option>';
        foreach ($load_tb as $lt) {
            echo '<option value="'.$lt['TABLE_NAME'].'">'.$lt['TABLE_NAME'].'</option>';
        }
        echo '</select>';
        echo '<style>
                 #openTable{
                     width:350px;   
                 }
                </style> ';
    }
    
    function write(){ 
        $logged_nip = $this->user->gNIP;

        /*backback  5
        createname  itemas
        dbf_path    DATA/SALES
        field_view  C_ITENO
        last_update D_LSTUPDT
        nm_dbf  itemas
        openDatabase    plc
        openModule  schedulercheck
        primary_key C_ITENO*/

        //print_r($_POST);
        //exit;

        $createname = $this->input->post('createname');
        $openModule = $this->input->post('openModule'); 

        $primary_key = $this->input->post('primary_key'); 
        $forign_key = $this->input->post('forign_key');

        

        $field_view = $this->input->post('field_view'); 
        $dbf_path = $this->input->post('dbf_path'); 
        $nm_dbf = $this->input->post('nm_dbf'); 
        $last_update = $this->input->post('last_update'); 
        $backback = $this->input->post('backback'); 
        
        $selectCompany = $this->input->post('selectCompany');  
        $openTable = $this->input->post('openTable'); 
        $openDatabase = $this->input->post('openDatabase'); 

        $r = array(
            'Nama Controller' => $createname,
            'Nama Module' => $openModule,
            'Nama Database' => $openDatabase,
            'Nama Table' => $openTable,
            'Generate By' => 'Softdev 2('.$logged_nip.')',
            );

        $createname_up = strtoupper($createname); 
        $createname_space = strtolower(str_replace(' ', '_', $createname));



        //Create Controller Folder
        $path1 = realpath("modules/".$openModule);
        if(!file_exists($path1."/controllers")){
            if (!mkdir($path1."/controllers", 0777, true)) { 
                die('Failed');
            }
        } 

        //Create View Folder

        // $path2 = realpath("modules/".$openModule);
        // if(!file_exists($path2."/views")){
        //     if (!mkdir($path2."/views", 0777, true)) { 
        //         die('Failed');
        //     }
        // }  

        //Create Controller Struktur ERP
        /*
            example :
            modules/ariesERP/ 
        */

 
        $html =" 
        <?php
        //ini_set('max_execution_time', 0);

        /* Generated by Softdev 2 ERP CRUD Generator ".date('Y-m-d H:i:s')." */
        /* Location: ./modules/".$openModule."/controllers/".$createname_space.".php */
        /* Please DO NOT modify this information : */ 
        "; 

        $html .=" 
          /*------------------------------------------------------New------------------------------------------------------*/
            \$scheduler_name='".$createname."';
            include('syslog_fwd.php'); 
            ini_set('max_execution_time', 0);

            error_reporting(E_ALL);
            set_error_handler('myErrorHandler');
           
            ini_set('log_errors', '1');
            ini_set('display_errors', '0');



            function myErrorHandler(\$errno, \$errstr, \$errfile, \$errline)
            {
                \$scheduler_name='".$createname."';
                if (!(error_reporting() & \$errno)) {
                   // This error code is not included in error_reporting, so let it fall
                   // through to the standard PHP error handler
                   return false;
                }

                 switch (\$errno) {
                 case E_USER_ERROR:
                     echo '<b>My ERROR</b> [\$errno] \$errstr<br />';
                     echo '  Fatal error on line \$errline in file \$errfile';
                     echo ', PHP ' . PHP_VERSION . ' (' . PHP_OS . ')<br />';
                     echo 'Aborting...<br />';

                      \$phrase  = \$errstr;
                      \$healthy = ['(', ')'];
                      \$yummy   = ['*'];
                      \$newPhrase = str_replace(\$healthy, \$yummy, \$phrase);

                      
                     SendToSyslog('sch_'.\$scheduler_name,\$newPhrase);
                     exit(1);
                     break;

                 case E_USER_WARNING:
                     echo '<b>My WARNING</b> [\$errno] $errstr<br />';
                     \$message = '<b>My WARNING</b> [\$errno] \$errstr<br />';
                     SendToSyslog('sch_'.\$scheduler_name,\$message);
                     break;

                 case E_USER_NOTICE:
                     echo '<b>My NOTICE</b> [\$errno] \$errstr<br />';
                      \$phrase  = \$errstr;
                      \$healthy = ['(', ')'];
                      \$yummy   = ['*'];
                      \$newPhrase = str_replace(\$healthy, \$yummy, \$phrase);

                      
                     SendToSyslog('sch_'.\$scheduler_name,\$newPhrase);
                     
                     break;

                 default:
                     echo 'Unknown error type: ['.\$errno.'] '.\$errstr.' line '.\$errline.'<br />'; 

                      \$phrase  = \$errstr;
                      \$healthy = ['(', ')'];
                      \$yummy   = ['*'];
                      \$newPhrase = str_replace(\$healthy, \$yummy, \$phrase);

                      
                     SendToSyslog('sch_'.\$scheduler_name,\$newPhrase);

                     break;
                 }

                

               /* Don't execute PHP internal error handler */
               return true;
            }

         
          

          /*------------------------------------------------------New------------------------------------------------------*/


        ";


        $html .=" 
        /*------------------------------------------------------Instuction------------------------------------------------------*/
        /*
         hal hal yang perlu diperhatikan untuk diganti variablenya adalah sbb:
              \$selectCompany='".$selectCompany."'; 
         1. koneksi mysql
               \$host = '10.1.49.6';
               \$user = 'nplnet';
               \$pass = 'nplnet01';
               \$db='".$openDatabase."';


         2. ODBC Connection 
               \$conn_db=odbc_connect('debef','','');

         3. Parameter 
               - \$scheduler_name='".$createname."';
               - \$BackdateI='360';
               - \$tbsql='".$openDatabase.".".$nm_dbf."';
               - \$pk=odbc_result(\$rs,'".$primary_key."');
               - \$fPk='C_FACCODE';
               - \$pkv=odbc_result(\$rs,'".$primary_key."').' - '.odbc_result(\$rs,'".$field_view."');
               - \$tbsch = 'plc2.scheduler_score';
               - \$dbFile='".$nm_dbf."';
               - \$dbfFile = realpath('//10.1.48.21/Sys2/".$dbf_path."/".$nm_dbf.".dbf');
               - \$sql='SELECT * FROM '.\$dbFile.' where d_lastupdt BETWEEN #\$tgl1# AND #\$tgl2#';


         4. Refference 
            - https://www.connectionstrings.com/dbf-foxpro/
            - https://www.pcreview.co.uk/threads/import-dbf-files-with-memo-fields.2651051/
            - http://php.net/manual/en/function.odbc-exec.php

      */

        /*------------------------------------------------------Instuction------------------------------------------------------*/
        "; 

        $html .=" 
            error_reporting(E_ALL);
            ini_set('display_errors', '1');

        ";

        $html .=" 
           /*-----------------------------------------------------Mysql Connection Start
              ------------------------------------------------------
               \$host = '10.1.49.8';
               \$user = 'nplnet';
               \$pass = 'nplnet01';
               \$db='".$openDatabase."';

              \$conn = mysql_connect(\$host, \$user, \$pass);
              if (\$conn) {
                  mysql_select_db(\$db, \$conn);
              } else {
                 die('Error : '.mysqli_error());
              }
              */
              include('koneksi2.php');
           /*------------------------------------------------------Mysql Connection End------------------------------------------------------*/

        ";

       

        $html .=" 
             /*-----------------------------------------------------ODBC Connection Start-----------------------------------------------------*/

            \$cari = ".'"'."CommandLine like '%".$createname.".bat%'".'"'."; 
            \$cmd ='wmic process where ".'"'."'.\$cari.'".'"'." get commandline';
            exec(\$cmd, \$output, \$return_var);
            if(count(\$output)>5){ 
               SendToSyslog('sch_'.\$scheduler_name,'Scheduler sedang Running');
               die();
            }else{
              SendToSyslog('sch_'.\$scheduler_name,'Scheduler Running Start');
            \$db='".$openDatabase."';
            \$dbfFile = realpath('G:/".$dbf_path."/".$nm_dbf.".dbf');
            \$dbfDir = dirname(\$dbfFile);
            \$dbfDir1 = 'G:/".$dbf_path."';
            \$conn_db = odbc_connect('Driver={Microsoft Visual FoxPro Driver};SourceType=DBF;SourceDB='.\$dbfDir1.';Exclusive=No;Collate=Machine;NULL=NO;DELETED=YES;BACKGROUNDFETCH=NO;' , '', '');
         
            //$conn_db=odbc_connect('vfpDriver','','');
             if (!\$conn_db)
             {
                exit('Connection Failed: ' . \$conn_db);
             }else{
                //echo 'Connected';
                //exit;
             }  
            /*------------------------------------------------------ODBC Connection End------------------------------------------------------*/
        ";

        $html .=" 
          /*------------------------------------------------------Parameter Start------------------------------------------------------*/
              \$selectCompany='".$selectCompany."'; 
              \$scheduler_name='".$createname."';
              /* \$tgl1='2017-07-06';
                 \$tgl2='2017-07-07';
              */

              /*number of days back from now */
              \$BackdateI='".$backback."';
              \$last_update='".$last_update."';

              
              \$tgl2 = date('Ymd');
              \$backback = strtotime('- '.\$BackdateI.' days', strtotime(\$tgl2));
              \$tgl1 = date('Ymd', \$backback);

              /*Setting Table Destination*/
              \$tbsql='".$openDatabase.".".strtolower($nm_dbf)."';

              \$dbFile='".$nm_dbf."';

              

              /*flag finish running*/
              \$isFinish = false;


           /*------------------------------------------------------Parameter End------------------------------------------------------*/
        ";

        $html .=" 
                /* Select data from DBF*/
                /*parsing parameter with hastag (#) */
                 //\$sql='SELECT * FROM '.\$dbFile.' where d_lastupdt BETWEEN #\$tgl1# AND #\$tgl2#';

                 

                if(\$last_update<>'-'){
                  \$sql = 'SELECT * From "."'.\$dbFile.'"."  WHERE DTOS("."'.\$dbFile.'"."."."'.\$last_update.'".") BETWEEN ".'"'."'.\$tgl1.'".'"'."  and ".'"'."'.\$tgl2.'".'"'." ';
                }else{
                  \$sql='SELECT * FROM "."'.\$dbFile.'"." ';
                }

                /*new*/
                SendToSyslog('sch_'.\$scheduler_name,'Select Data DBF : '.\$sql);

                 
                 //echo \$sql;
                 //exit;
             
                \$rs=odbc_exec(\$conn_db,\$sql);

                if (!\$rs)
                 {
                    /*new*/
                    SendToSyslog('sch_'.\$scheduler_name,'Failed Select Data DBF : '.\$sql);
                    exit('ODBC Exec failed: ' . \$sql);
                 }else{
                    //echo 'Success Query';
                    //exit;
                 }  


                 /*Get Field Name*/
                 \$arrNmKolom = array();
                 
                 for(\$i=1; \$i <= odbc_num_fields(\$rs); \$i++){
                  /*push field name to array*/
                  array_push(\$arrNmKolom,odbc_field_name(\$rs, \$i) );

                 }

                 /*--------Create Table if not exist -------*/
                    \$create_table='CREATE TABLE IF NOT EXISTS  "."'.\$tbsql.'"."   (
                    id int(11) NOT NULL AUTO_INCREMENT,';
                    foreach (\$arrNmKolom as \$iKol => \$vKolom) {
                       
                         \$kDKolom=substr(\$vKolom,0,1);
                         \$KolomType=get_type(\$kDKolom);

                         \$create_table.=\$vKolom.' '.\$KolomType['jenis'].' '.\$KolomType['fld'].' DEFAULT NULL, ';   
                       
                    }

                    \$create_table.='D_export datetime DEFAULT CURRENT_TIMESTAMP,
                                    iCompanyID int(11),
                                    dCreate datetime DEFAULT NULL,
                                    dUpdate datetime DEFAULT NULL,
                                    cCreate Varchar(10) DEFAULT NULL,
                                    cUpdate Varchar(10) DEFAULT NULL,
                                    lDeleted int(1) DEFAULT 0,
                             PRIMARY KEY (id)
                       ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;';

                     runSQLCreateTable(\$create_table,\$scheduler_name);

                 /*--------Create Table if not exist -------*/ 
        ";

        $html .=" 
                   /*------------------------------------------------Alter Column IF Exist  ------------------------------------------------------*/

                    \$altTable = runSQLAlterTableGetField(\$db,\$dbFile,\$scheduler_name);
                    \$setArray = array();
                    \$setArrayAlter = array();


                    foreach (\$altTable['fields'] as \$dt) {
                      array_push(\$setArray,\$dt['COLUMN_NAME']);
                    }
                         
                    foreach (\$arrNmKolom as \$iKol2 => \$vKolom2) {
                      if(!in_array(\$vKolom2,\$setArray)){
                        array_push(\$setArrayAlter,\$vKolom2);
                      }
                    }

                    if(!empty(\$setArrayAlter)){
                      foreach (\$setArrayAlter as \$key => \$valueIns) {
                        \$kDKolom=substr(\$valueIns,0,1);
                        \$KolomType=get_type(\$kDKolom);    
                        \$sqlAlter = 'ALTER TABLE "."'.\$db.'"."."."'.\$dbFile.'"." ADD '.\$valueIns.' '.\$KolomType['jenis'].' '.\$KolomType['fld'].' NULL';  
                          runSQLAlterTableProses(\$sqlAlter,\$scheduler_name);
                      }
                    } ";

        $html .=" 
                /*------------------------------------------------Processing Data Start------------------------------------------------------*/
                 //print_r(\$arrNmKolom);
                //function processingData(){
                 if (!\$rs)
                 {
                    exit('Error in SQL');
                 }

                 // \$html used to show data
                 \$html  ='';
                 \$html .= '<table>';
                 \$html .= '<tr>';
                 for(\$i=1; \$i <= odbc_num_fields(\$rs); \$i++){
                    \$html .= '<th>'.odbc_field_name(\$rs, \$i).'</th>'; 
                 

                 }
                 \$html .= '</tr>';

                 
                 \$arriSi= array(); 
                while (odbc_fetch_row(\$rs))
                {

                    /*describe PK Column & get Value of PK*/
                    \$pk=odbc_result(\$rs,'".$primary_key."'); 
                    ";
                      //pecah forign key
                      if($forign_key=="-" || $forign_key=="0" || $forign_key==""){
                        $sqlSearch= "";
                        $sqlTamb="";
                      }else{
                        $forexp = explode(',', $forign_key);
                        $sqlSearch= "";
                        $sqlTamb="";
                        $sqlTamb1="";
                        if(!empty($forexp)){
                          $i = 0;
                          foreach ($forexp as $fk=>$v) {
                            $i++;
                            $sqlSearch.="\$fk_".$i."=odbc_result(\$rs,'".$v."');
                            ";

                            $sqlSearch.="  if(trim(\$fk_".$i.")==''){
                                              \$fk_".$i." = ' is NULL';
                                            }else{
                                              
                                              \$fk_".$i." =  ".'" = '."'".'"'.".\$fk_".$i.".".'"'."'".'"'.";
                                            }
                                        ";

                            $sqlTamb.=" AND a.".$v." "."'.\$fk_".$i.".'"."";
                            $sqlTamb1.=" AND ".$v." "."'.\$fk_".$i.".'"."";
                          }
                        }
                      }
                      

             $html .=$sqlSearch."
                    \$fPk='".$primary_key."';
                    /*describe PK show when transfering*/
                    //\$pkv= \$pk;
                    \$pkv=odbc_result(\$rs,'".$primary_key."').' - '.odbc_result(\$rs,'".$field_view."');
                   
                    /*cek data existing in mysql table*/
                    /*param use here*/

                    \$sqlUdah = 'select a.* from '.\$tbsql.' a where a.'.\$fPk.'= ".'"'."'.\$pk.'".'"'." ".$sqlTamb." and a.iCompanyID= '.\$selectCompany.' '"." ;

                      \$phrase  = \$sqlUdah;
                      \$healthy = [ ".'"'."'".'"'." , "."'".'"'."'"."];
                      \$yummy   = ['_'];
                      \$newPhrase = str_replace(\$healthy, \$yummy, \$phrase);

                    /*new*/
                    SendToSyslog('sch_'.\$scheduler_name,'Check exist data: '.\$newPhrase);

                    \$rowcount = runSQLRaw(\$sqlUdah,\$scheduler_name); 

                    if (\$rowcount['rowcount'] > 0) 
                    {
                      // updating record when exists
                      \$sa = '';
                      echo 'Updating ... '.\$pk;
                      \$sa.='UPDATE '.\$tbsql.' SET ';
                      \$i=0;

                        foreach (\$arrNmKolom as \$fd => \$vd) {
                            \$isinya = str_replace(".'"'."'".'"'.", '', odbc_result(\$rs,\$vd)); 
                            if(trim(\$isinya)<>''){
                              if(trim(\$isinya)=='1899-12-30'){
                                \$isinya = 'NULL';
                              }else{
                               \$isinya = ".'"'."'".'".'." \$isinya ".".".'"'."'".'"' .";
                              }
                            }else{
                               \$isinya = 'NULL';
                            }


                            if(\$i==0){
                               \$sa.= \$vd.'="."'"." .\$isinya;
                            }else{
                              \$sa.= ".'","'.".\$vd.'="."'"." .\$isinya;
                            }

                            \$i++;
                        }


                
                        \$sa.=' where ".''." "."'"."  .\$fPk. "."'"." ".''."  = ".'"'.""."'".".\$pk."."'"."".'"'." ".$sqlTamb1."   AND iCompanyID= '.\$selectCompany.' '"." ;
                   
                        echo '<br>'; 
                        \$runSQLInsertUpdate = runSQLUpdate(\$sa,\$scheduler_name);
                        echo \$runSQLInsertUpdate['message'];
                        echo '<br>';

                    }else{
                       \$sa = '';
                       echo 'Inserting ... '.\$pk;
                       \$sa .='INSERT INTO '.\$tbsql.'(';
                          \$ic=0;
                          foreach (\$arrNmKolom as \$fd => \$vd) {
                                if(\$ic==0){
                                   \$sa.=\$vd;
                                }else{
                                   \$sa.="."','" ." .\$vd;
                                }
                                \$ic++;
                          }
                          \$sa.="."',iCompanyID'" .";
                       \$sa.=')VALUES(';
                       \$iR=0;

                        foreach (\$arrNmKolom as \$fd => \$vd) {
                            \$isinya = str_replace(".'"'."'".'"'.", '', odbc_result(\$rs,\$vd)); 
                            if(trim(\$isinya)<>''){
                              if(trim(\$isinya)=='1899-12-30'){
                                \$isinya = 'NULL';
                              }else{
                               \$isinya = ".'"'."'".'".'." \$isinya ".".".'"'."'".'"' .";
                              }
                            }else{
                               \$isinya = 'NULL';
                            }


                            if(\$iR==0){
                               \$sa.= \$isinya;
                            }else{
                                \$sa.="."','".".\$isinya;
                            }
                            
                            \$iR++;
                        }
                        \$sa.="."','".".\$selectCompany;

                        \$sa.=');';
                       echo '<br>';

                        \$runSQLInsertUpdate = runSQLInsert(\$sa,\$scheduler_name);
                        echo \$runSQLInsertUpdate['message'];
                        echo '<br>';



                    }
                }
         
                \$html .= '</table>';
                \$html .= '<br>';
         
                 /* Finish Processing Data*/
                 \$isFinish = true;
                 schLogger(\$scheduler_name,\$isFinish,'done','Everything is OK');

                 /*close odbc Connection*/
                 odbc_close(\$conn_db);

                 SendToSyslog('sch_'.\$scheduler_name,'Scheduler Running Finish');

              //}
                
           /*------------------------------------------------------Processing Data End------------------------------------------------------*/
         }
        ";

        $html .="

                function schLogger(\$sched,\$res,\$notes,\$warning){
                  /*Setting Table score*/
                  \$tbsch = 'plc2.scheduler_score';

                  \$now = date('Y-m-d H:i:s');
                  \$cType = 'php';
                  if(\$res===True){
                     \$iStatus = 1;
                  }else{
                     \$iStatus = 0;
                  } 

               }


                function get_type(\$type='V'){
                  switch (\$type) {
                     case 'C': //Varchar
                     case 'c': //Varchar
                        \$re['jenis']='varchar';
                        \$re['fld']='(255)';
                        break;
                     case 'D': //Varchar
                     case 'd': //Varchar
                        \$re['jenis']='date';
                        \$re['fld']='';
                        break;
                     case 'N': // Number
                     case 'n': // Number
                        \$re['jenis']='float';
                        \$re['fld']='';
                        break;
                     case 'L': // Bit
                     case 'l': // Bit
                        \$re['jenis']='int';
                        \$re['fld']='(11)';
                        break;
                     
                     default:
                        \$re['jenis']='varchar';
                        \$re['fld']='(255)';
                        break;
                  }

                  return \$re;

                }    

                    
             "
          
        ;

       

        
        $dir = $path1."/controllers";
        $file_to_write = $createname_space.'.php';

        $r = array(
            'Nama_Controller' => $createname_space,
            'Nama_Module' => $openModule,
            'Nama_Database' => $openDatabase,
            'Nama_Table' => $openTable,
            'Generate_By' => 'Softdev 2',
        ); 

        $pk =1;
        if($pk==0){
             $r['status'] = false;
             $r['pk'] = 0;
        }else{
            if (file_exists($dir . '/' . $file_to_write)) {
                $r['status'] = false;
                $r['pk'] = 1;
            }else { 
                
                $r['pk'] = 1;
                $file = fopen($dir . '/' . $file_to_write,"w"); 
                $content_to_write = $html;
                if(fwrite($file, $content_to_write)){
                  $r['status'] = true; 
                }else{
                  $r['status'] = false; 
                  $r['message'] = 'gagal create file'; 
                } 
                fclose($file);
            }
        }
        
 
        echo json_encode($r); 
    }
    public function output(){
        $this->index($this->input->get('action'));
    }

}
