 
        <?php
        /* Generated by Sovdev 2 ERP CRUD Generator 2018-10-30 12:33:13 */
        /* Location: ./modules/menu/controllers/trf_ds.php */
        /* Please DO NOT modify this information : */ 
         
        if ( ! defined('BASEPATH')) exit('No direct script access allowed');
        class trf_ds extends MX_Controller {
            function __construct() {
                 parent::__construct();
                    $this->db_schedulercheck = $this->load->database('schedulercheck',false, true);
                    $this->load->library('auth');
                    $this->dbset = $this->load->database('hrd', true);
                    $this->user = $this->auth->user();
                    $this->url = 'trf_ds'; 
                //$this->user = $this->auth->user();
            }
            function index($action = '') {
                $action = $this->input->get('action');
                //Bikin Object Baru Nama nya $grid      
                $grid = new Grid;
                $grid->setTitle('Master Area DS');
                $grid->setTable('hrd.ss_trf_area');      
                $grid->setUrl('trf_ds');

                //List Table
                $grid->addList('cKode_area','vNama_area','employee.vName','iAktif'); 
                $grid->setSortBy('id');
                $grid->setSortOrder('desc');  

                //List field
                $grid->addFields('cKode_area','vNama_area','cPic','iAktif'); 

                //Setting Grid Width Name 
                /*
                    Kamu bisa merubah nama label dari sini, Contoh :
                    $grid->setLabel('nama field','nama field yang akan diubah');

                */
        
                $grid->setWidth('cKode_area', '100');
                $grid->setAlign('cKode_area', 'left');
                $grid->setLabel('cKode_area','Kode Area');

                $grid->setWidth('employee.vName', '200');
                $grid->setAlign('employee.vName', 'left');
                $grid->setLabel('employee.vName','Name');
                
            
                $grid->setWidth('vNama_area', '100');
                $grid->setAlign('vNama_area', 'left');
                $grid->setLabel('vNama_area','Nama Area');
            
                $grid->setWidth('cPic', '100');
                $grid->setAlign('cPic', 'left');
                $grid->setLabel('cPic','PIC');

                $grid->setLabel('iAktif','Status');


                $grid->changeFieldType('iAktif','combobox','',array(''=>'Pilih',1=>'Aktif',0=>'Tidak aktif'));
            
                //Example modifikasi GRID ERP
                /*
                    - Set Query
                        $grid->setQuery('lDeleted = 0 ', null); 
                        $grid->setQuery('plc2_upb.iupb_id IN (select distinct(bk.iupb_id) from plc2.plc2_upb_spesifikasi_fg bk where bk.iappqa=2 and bk.ldeleted=0)', null);  

                    - Join Table
                        $grid->setJoinTable('hrd.employee', 'employee.cNip = pk_master.vnip', 'inner');

                    - Change Field Name
                        $grid->changeFieldType('ideleted','combobox','',array(''=>'Pilih',0=>'Aktif',1=>'Tidak aktif'));
                */

                 //set search
                $grid->setJoinTable('hrd.employee', 'employee.cNip = ss_trf_area.cPic', 'inner');
                $grid->setSearch('cKode_area','vNama_area','iAktif','employee.vName');
                
                //set required
                $grid->setRequired('cKode_area','vNama_area','cPic','iAktif'); 

                $grid->setGridView('grid');

                switch ($action) {
                    case 'json':
                            $grid->getJsonData();
                            break;
                    case 'view':
                            $grid->render_form($this->input->get('id'), true);
                            break;
                    case 'create':
                            $grid->render_form();
                            break;
                    case 'createproses':
                            echo $grid->saved_form();
                            break;
                    case 'update':
                            $grid->render_form($this->input->get('id'));
                            break;
                    case 'updateproses':
                            echo $grid->updated_form();
                            break;
                    case 'delete':
                            echo $grid->delete_row();
                            break; 
                    case 'getEmployeeDS':
                            echo $this->getEmployeeDS();
                            break;              

                    /*
                        //Ini Merupakan Standart Case Untuk Approve

                        case 'approve':
                            echo $this->approve_view();
                            break;
                        case 'approve_process':
                            echo $this->approve_process();
                            break;
                        case 'reject':
                            echo $this->reject_view();
                            break;
                        case 'reject_process':
                            echo $this->reject_process();
                            break; 
                    */ 
                    default:
                            $grid->render_grid();
                            break;
                }
            }
            //Create Manipulate Field 

            //Jika Ingin Menambahkan Seting grid seperti button edit enable dalam kondisi tertentu
            /* 
            function listBox_Action($row, $actions) {
                if ($row->vNo_Or<>'' || $row->vNo_Or<>NULL) { 
                        unset($actions['edit']);
                }
                return $actions;
            } 
            */

            function getEmployeeDS() {
                    $term = $this->input->get('term');      
                    $data = array();
                    $sql = "select * 
                            from hrd.employee a
                            join hrd.company b on a.iCompanyID=b.iCompanyId
                            where 
                            a.lDeleted=0 AND a.iDivisionID=6 #Divisi MiS
                            and  a.dresign = '0000-00-00'
                            and  a.vName like '%".$term."%'
                            ";
                    $query = $this->dbset->query($sql);
                    if ($query->num_rows > 0) {
                        foreach($query->result_array() as $line) {
                            $row_array['value'] = trim($line['cNip']).' - '.trim($line['vName']);
                            $row_array['id']    = $line['cNip'];
                            $row_array['nama']    = trim($line['vName']);
                            $row_array['company']    = $line['vCompName'];
                            $row_array['status']    = $line['cEmpStat'];
                            $row_array['dPassProbation']    = $line['dPassProbation'];
                            

                            array_push($data, $row_array);
                        }
                    }
                    echo json_encode($data);
                    exit;
            }

            function insertBox_trf_ds_cPic($field, $id, $value, $rowData) {
                $url=base_url().'processor/schedulercheck/trf/ds?action=getEmployeeDS';
                $rr = $this->db_schedulercheck->get_where('hrd.ss_trf_area', array('cPic'=>$rowData['cPic']));
                $cPic='';
                $namepic='';
                if ($rr->num_rows()>=1) {
                    $rows=$rr->row_array();
                    if($rows['cPic']!=''){
                        $sql="select * from hrd.employee em where em.cNip='".$rows['cPic']."'";
                        $dt=$this->db_schedulercheck->query($sql)->row_array();
                        $cPic=$dt['cNip'];
                        $namepic=$dt['cNip']." - ".$dt['vName'];
                        
                    }

                }
                $re="<input name='trf_ds_cPic' id='trf_ds_cPic' type='hidden' value='".$cPic."' class='' /><input name='trf_ds_cPic_dis' id='trf_ds_cPic_dis' type='text' size='20' value='".$namepic."' class='' />";
                $re.='<script>
                    var config3 = {
                        source: function( request, response) {
                            $.ajax({
                                url: "'.$url.'",
                                dataType: "json",
                                data: {
                                    term: request.term,
                                },
                                success: function( data ) {
                                    response( data );
                                }
                            });
                        },
                        select: function(event, ui){
                            $( "#trf_ds_cPic" ).val(ui.item.id);
                            $( "#trf_ds_cPic_dis" ).val(ui.item.value);
                            return false;
                        },
                        minLength: 2,
                        autoFocus: true,
                    };

                    $( "#trf_ds_cPic_dis" ).livequery(function() {
                        $( this ).autocomplete(config3);
                    });
                </script>';
                return $re;
            }

            function updateBox_trf_ds_cPic($field, $id, $value, $rowData) {
                $url=base_url().'processor/schedulercheck/trf/ds?action=getEmployeeDS';
                $rr = $this->db_schedulercheck->get_where('hrd.ss_trf_area', array('cPic'=>$rowData['cPic']));
                $cPic='';
                $namepic='';
                if ($rr->num_rows()>=1) {
                    $rows=$rr->row_array();
                    if($rows['cPic']!=''){
                        $sql="select * from hrd.employee em where em.cNip='".$rows['cPic']."'";
                        $dt=$this->db_schedulercheck->query($sql)->row_array();
                        $cPic=$dt['cNip'];
                        $namepic=$dt['cNip']." - ".$dt['vName'];
                        
                    }

                }
                $re="<input name='trf_ds_cPic' id='trf_ds_cPic' type='hidden' value='".$cPic."' class='' /><input name='trf_ds_cPic_dis' id='trf_ds_cPic_dis' type='text' size='20' value='".$namepic."' class='' />";
                $re.='<script>
                    var config3 = {
                        source: function( request, response) {
                            $.ajax({
                                url: "'.$url.'",
                                dataType: "json",
                                data: {
                                    term: request.term,
                                },
                                success: function( data ) {
                                    response( data );
                                }
                            });
                        },
                        select: function(event, ui){
                            $( "#trf_ds_cPic" ).val(ui.item.id);
                            $( "#trf_ds_cPic_dis" ).val(ui.item.value);
                            return false;
                        },
                        minLength: 2,
                        autoFocus: true,
                    };

                    $( "#trf_ds_cPic_dis" ).livequery(function() {
                        $( this ).autocomplete(config3);
                    });
                </script>';
                return $re;
            }

            function insertBox_trf_ds_cKode_area($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';
                return $return;
            }
            function updateBox_trf_ds_cKode_area($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "50"  value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 50) {
                                            this.value = this.value.substring(0, 50);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(50 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">50</span> karakter<br/>';

                } 
                return $return;
            }   
            
            function insertBox_trf_ds_vNama_area($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "15" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 15);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(15 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">15</span> karakter<br/>';
                return $return;
            }
            function updateBox_trf_ds_vNama_area($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "15"  value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 15) {
                                            this.value = this.value.substring(0, 15);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(15 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">15</span> karakter<br/>';

                } 
                return $return;
            }   
            
            function insertBox_trf_ds_cPic1($field, $id) {
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "100" />';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 250) {
                                            this.value = this.value.substring(0, 100);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(100 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">100</span> karakter<br/>';
                return $return;
            }
            function updateBox_trf_ds_cPic1($field, $id, $value, $rowData) {
                if ($this->input->get('action') == 'view') {
                     $return= $value; 
                }else{
                $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30" maxlength = "100"  value="'.$value.'"/>';
                $return .= '<script>
                                $("#'.$id.'").keyup(function() {
                                    var len = this.value.length;
                                        if (len >= 100) {
                                            this.value = this.value.substring(0, 100);
                                        }
                                    $("#maxlengthnote_'.$id.'").text(100 - len);
                                });
                             </script>';
                $return .= '<br/>tersisa <span id="maxlengthnote_'.$id.'">100</span> karakter<br/>';

                } 
                return $return;
            }   
            
            /*
                //Ini Merupakan Standart Approve yang digunakan di erp
 
                function approve_view() {
                    $echo = '<script type="text/javascript">
                                 function submit_ajax(form_id) {
                                    return $.ajax({
                                        url: $("#"+form_id).attr("action"),
                                        type: $("#"+form_id).attr("method"),
                                        data: $("#"+form_id).serialize(),
                                        success: function(data) {
                                            var o = $.parseJSON(data);
                                            var last_id = o.last_id;
                                            var url = "'.base_url().'processor/menu/trf_ds";                             
                                            if(o.status == true) { 
                                                $("#alert_dialog_form").dialog("close");
                                                     $.get(url+"?action=update&id="+last_id, function(data) {
                                                     $("div#form_trf_ds").html(data);
                                                     
                                                });
                                                
                                            }
                                                reload_grid("grid_trf_ds");
                                        }
                                        
                                     })
                                 }
                             </script>';
                    $echo .= '<h1>Approve</h1><br />';
                    $echo .= '<form id="form_trf_ds_approve" action="'.base_url().'processor/menu/trf_ds?action=approve_process" method="post">';
                    $echo .= '<div style="vertical-align: top;">';
                    $echo .= 'Remark : 
                            <input type="hidden" name="id" value="'.$this->input->get('id').'" />
                            <input type="hidden" name="lvl" value="'.$this->input->get('lvl').'" />
                            <input type="hidden" name="group_id" value="'.$this->input->get('group_id').'" />
                            <input type="hidden" name="modul_id" value="'.$this->input->get('modul_id').'" />
                            <textarea name="vRemark"></textarea>
                    <button type="button" onclick="submit_ajax(\'form_trf_ds_approve\')">Approve</button>';
                        
                    $echo .= '</div>';
                    $echo .= '</form>';
                    return $echo;
                } 
 
                function approve_process() {
                    $post = $this->input->post();
                    $cNip= $this->user->gNIP;
                    $vName= $this->user->gName;
                    $id = $post['id'];
                    $vRemark = $post['vRemark'];
                    $lvl = $post['lvl'];
 
                    //Letakan Query Update approve disini

                    $data['status']  = true;
                    $data['last_id'] = $post['id'];
                    return json_encode($data);
                }
            */

        
            /*
                //Ini Merupakan Standart Reject yang digunakan di erp

                function reject_view() {
                    $echo = '<script type="text/javascript">
                                 function submit_ajax(form_id) {
                                    var remark = $("#trf_ds_remark").val();
                                    if (remark=="") {
                                        alert("Remark tidak boleh kosong ");
                                        return
                                    }

                                    return $.ajax({
                                        url: $("#"+form_id).attr("action"),
                                        type: $("#"+form_id).attr("method"),
                                        data: $("#"+form_id).serialize(),
                                        success: function(data) {
                                            var o = $.parseJSON(data);
                                            var last_id = o.last_id;
                                            var url = "'.base_url().'processor/menu/trf_ds";                             
                                            if(o.status == true) { 
                                                $("#alert_dialog_form").dialog("close");
                                                     $.get(url+"?action=update&id="+last_id, function(data) {
                                                     $("div#form_trf_ds").html(data);
                                                     
                                                });
                                                
                                            }
                                                reload_grid("grid_trf_ds");
                                        }
                                        
                                     })
                                 }
                             </script>';
                    $echo .= '<h1>Reject</h1><br />';
                    $echo .= '<form id="form_trf_ds_reject" action="'.base_url().'processor/menu/trf_ds?action=reject_process" method="post">';
                    $echo .= '<div style="vertical-align: top;">';
                    $echo .= 'Remark : 
                            <input type="hidden" name="id" value="'.$this->input->get('id').'" />
                            <input type="hidden" name="lvl" value="'.$this->input->get('lvl').'" />
                            <input type="hidden" name="group_id" value="'.$this->input->get('group_id').'" />
                            <input type="hidden" name="modul_id" value="'.$this->input->get('modul_id').'" />
                            <textarea name="vRemark" id="reject_trf_ds_remark"></textarea>
                    <button type="button" onclick="submit_ajax(\'form_trf_ds_reject\')">Reject</button>';
                        
                    $echo .= '</div>';
                    $echo .= '</form>';
                    return $echo;
                }


                
                function reject_process() {
                    $post = $this->input->post();
                    $cNip= $this->user->gNIP;
                    $vName= $this->user->gName;
                    $id = $post['id'];
                    $vRemark = $post['vRemark'];
                    $lvl = $post['lvl'];
 
                    //Letakan Query Update approve disini

                    $data['status']  = true;
                    $data['last_id'] = $post['id'];
                    return json_encode($data);
                }
            */

        
            //Standart Setiap table harus memiliki dCreate , cCreated, dupdate, cUpdate
            function before_insert_processor($row, $postData) {
                $postData['dCreate'] = date('Y-m-d H:i:s');
                $postData['cCreated']=$this->user->gNIP;
                return $postData;

            }
            function before_update_processor($row, $postData) {
                $postData['dupdate'] = date('Y-m-d H:i:s');
                $postData['cUpdate'] = $this->user->gNIP;
                return $postData; 
            }    
        
            function after_insert_processor($fields, $id, $postData) {
                //Example After Insert
                /*
                $cNip = $this->sess_auth->gNIP; 
                $sql = 'Place Query In Here';
                $this->db_schedulercheck->query($sql);
                */
            }
    
            function after_update_processor($fields, $id, $postData) {
                //Example After Update
                /*
                $cNip = $this->sess_auth->gNIP; 
                $sql = 'Place Query In Here';
                $this->db_schedulercheck->query($sql);
                */
            }
            function manipulate_update_button($buttons, $rowData) { 
                //Load Javascript In Here 
                if ($this->input->get('action') == 'view') {
                    unset($buttons['update']);
                }
                else{ 
                    
                }
                
                return $buttons;
            }
            //Output
            public function output(){
                $this->index($this->input->get('action'));
            }
        }