 
<?php
/* Generated by Softdev 2 ERP Module Generator 2019-02-03 21:40:25 */
/* Location: ./modules/pengujian/controllers/mt01.php */
/* Please DO NOT modify this information : */ 


/*
    Preparation 
    1. untuk load view halaman upload , file berada pada folder partial;
    2. lib auth untuk fungsi check modul



    Parameter need to be change after generate 
    1. FOLDER_APP => change to folder name where this controllers should be there
    2. Static Dropdown => change value for option
    3. Dynamic Dropdown => Change query for option

    Table Sample 
    test.item && test.item_file_upload




*/
 


 
if ( ! defined('BASEPATH')) exit('No direct script access allowed');
class mt01 extends MX_Controller {
    function __construct() {
        parent::__construct();
        /*$this->dbset = $this->load->database('schedulercheck',false, true);*/
        $this->load->library('auth');
        $this->db = $this->load->database('hrd',false, true);
        $this->user = $this->auth->user();

       /* $checkMod = $this->auth->modul_set($this->input->get('modul_id'));
        $this->validation =$checkMod['iValidation'];*/

    }

    function index($action = '') {
        $action = $this->input->get('action');
        //Bikin Object Baru Nama nya $grid      
        $grid = new Grid;
        $grid->setTitle('MT01');
        $grid->setTable('bbpmsoh.mt01');      
        $grid->setUrl('mt01');

        //List Table
        $grid->addList('vNo_transaksi','vNomor','vPerihal','dTanggal','iCustomer','vNama_produsen','iM_tujuan_pengujian','vNama_sample','iSubmit','iApprove'); 
        $grid->setSortBy('iMt01');
        $grid->setSortOrder('DESC');  

        //List field
        $grid->addFields('iSubmit','iApprove','vNo_transaksi','vNomor','vLampiran','vPerihal','dTanggal','iCustomer','vNama_produsen','vAlamat_produsen','iM_tujuan_pengujian','vTujuan_pengujian_ket','vNama_sample','iM_jenis_sediaan','iSudah_beredar','vZat_aktif','vBatch_lot','dTgl_produksi','dTgl_kadaluarsa','vNo_registrasi','vKemasan','iJumlah_diserahkan','vSuhu_penyimpanan','vPermohonan_lampiran','dTgl_ambil_sample','dTgl_serah_sample','vPimpinan_perusahaan'); 

        //Setting Grid Width Name 
        /*
        Kamu bisa merubah nama label dari sini, Contoh :
        $grid->setLabel('nama field','nama field yang akan diubah');

        */

        $grid->setWidth('vNo_transaksi', '100');
        $grid->setAlign('vNo_transaksi', 'left');
        $grid->setLabel('vNo_transaksi','No Transaksi');
    
        $grid->setWidth('vNomor', '100');
        $grid->setAlign('vNomor', 'left');
        $grid->setLabel('vNomor','Nomor');
    
        $grid->setWidth('vLampiran', '100');
        $grid->setAlign('vLampiran', 'left');
        $grid->setLabel('vLampiran','Lampiran ');
    
        $grid->setWidth('vPerihal', '100');
        $grid->setAlign('vPerihal', 'left');
        $grid->setLabel('vPerihal','Perihal');
    
        $grid->setWidth('dTanggal', '100');
        $grid->setAlign('dTanggal', 'left');
        $grid->setLabel('dTanggal','Tanggal');
    
        $grid->setWidth('iCustomer', '100');
        $grid->setAlign('iCustomer', 'left');
        $grid->setLabel('iCustomer','Customer');
    
        $grid->setWidth('vNama_produsen', '100');
        $grid->setAlign('vNama_produsen', 'left');
        $grid->setLabel('vNama_produsen','Nama Produsen');
    
        $grid->setWidth('vAlamat_produsen', '100');
        $grid->setAlign('vAlamat_produsen', 'left');
        $grid->setLabel('vAlamat_produsen','Alamat Produses');
    
        $grid->setWidth('iM_tujuan_pengujian', '100');
        $grid->setAlign('iM_tujuan_pengujian', 'left');
        $grid->setLabel('iM_tujuan_pengujian','Tujuan Pengujian');
    
        $grid->setWidth('vTujuan_pengujian_ket', '100');
        $grid->setAlign('vTujuan_pengujian_ket', 'left');
        $grid->setLabel('vTujuan_pengujian_ket','Keterangan Tujuan');
    
        $grid->setWidth('vNama_sample', '100');
        $grid->setAlign('vNama_sample', 'left');
        $grid->setLabel('vNama_sample','Nama Sample');
    
        $grid->setWidth('iM_jenis_sediaan', '100');
        $grid->setAlign('iM_jenis_sediaan', 'left');
        $grid->setLabel('iM_jenis_sediaan','Jenis Sediaan');
    
        $grid->setWidth('iSudah_beredar', '100');
        $grid->setAlign('iSudah_beredar', 'left');
        $grid->setLabel('iSudah_beredar','Informasi Peredaran di Indonesia');
    
        $grid->setWidth('vZat_aktif', '100');
        $grid->setAlign('vZat_aktif', 'left');
        $grid->setLabel('vZat_aktif','Zak Aktif / Strain');
    
        $grid->setWidth('vBatch_lot', '100');
        $grid->setAlign('vBatch_lot', 'left');
        $grid->setLabel('vBatch_lot','No Batch / Lot');
    
        $grid->setWidth('dTgl_produksi', '100');
        $grid->setAlign('dTgl_produksi', 'left');
        $grid->setLabel('dTgl_produksi','Tanggal Produksi');
    
        $grid->setWidth('dTgl_kadaluarsa', '100');
        $grid->setAlign('dTgl_kadaluarsa', 'left');
        $grid->setLabel('dTgl_kadaluarsa','Tanggal Kadaluarsa');
    
        $grid->setWidth('vNo_registrasi', '100');
        $grid->setAlign('vNo_registrasi', 'left');
        $grid->setLabel('vNo_registrasi','No Registrasi');
    
        $grid->setWidth('vKemasan', '100');
        $grid->setAlign('vKemasan', 'left');
        $grid->setLabel('vKemasan','Kemasan');
    
        $grid->setWidth('iJumlah_diserahkan', '100');
        $grid->setAlign('iJumlah_diserahkan', 'left');
        $grid->setLabel('iJumlah_diserahkan','Jumlah yang diserahkan ');
    
        $grid->setWidth('vSuhu_penyimpanan', '100');
        $grid->setAlign('vSuhu_penyimpanan', 'left');
        $grid->setLabel('vSuhu_penyimpanan','Suhu Penyimpanan');
    
        $grid->setWidth('vPermohonan_lampiran', '100');
        $grid->setAlign('vPermohonan_lampiran', 'left');
        $grid->setLabel('vPermohonan_lampiran','Permohonan ini dilampiri dengan  ');
    
        $grid->setWidth('dTgl_ambil_sample', '100');
        $grid->setAlign('dTgl_ambil_sample', 'left');
        $grid->setLabel('dTgl_ambil_sample','Tanggal Pengambilan Sample');
    
        $grid->setWidth('dTgl_serah_sample', '100');
        $grid->setAlign('dTgl_serah_sample', 'left');
        $grid->setLabel('dTgl_serah_sample','Tanggal Penyerahan Sample');
    
        $grid->setWidth('vPimpinan_perusahaan', '100');
        $grid->setAlign('vPimpinan_perusahaan', 'left');
        $grid->setLabel('vPimpinan_perusahaan','Pimpinan Perusahaan');
    
        $grid->setWidth('iSubmit', '100');
        $grid->setAlign('iSubmit', 'left');
        $grid->setLabel('iSubmit','Status Submit');
    
        $grid->setWidth('iApprove', '100');
        $grid->setAlign('iApprove', 'left');
        $grid->setLabel('iApprove','Status Approval');
    
//Example modifikasi GRID ERP
    //- Set Query
        /*if ($this->validation) {
            $grid->setQuery('lDeleted = 0 ', null); 
        }*/

        

/*
    - Set Query
        $grid->setQuery('lDeleted = 0 ', null); 
        $grid->setQuery('plc2_upb.iupb_id IN (select distinct(bk.iupb_id) from plc2.plc2_upb_spesifikasi_fg bk where bk.iappqa=2 and bk.ldeleted=0)', null);  

    - Join Table
        $grid->setJoinTable('hrd.employee', 'employee.cNip = pk_master.vnip', 'inner');

    - Change Field Name
        $grid->changeFieldType('ideleted','combobox','',array(''=>'Pilih',0=>'Aktif',1=>'Tidak aktif'));
*/

    //set search
        $grid->setSearch('vNo_transaksi','vNomor','vPerihal','iCustomer','vNama_produsen','iM_tujuan_pengujian','iSubmit','iApprove');
        
    //set required
        $grid->setRequired('vNo_transaksi','vNomor','vLampiran','vPerihal','dTanggal','iCustomer','vNama_produsen','vAlamat_produsen','iM_tujuan_pengujian','vTujuan_pengujian_ket','vNama_sample','iM_jenis_sediaan','iSudah_beredar','vZat_aktif','vBatch_lot','dTgl_produksi','dTgl_kadaluarsa','vNo_registrasi','vKemasan','iJumlah_diserahkan','vSuhu_penyimpanan','vPermohonan_lampiran','dTgl_ambil_sample','dTgl_serah_sample','vPimpinan_perusahaan','lDeleted','iSubmit','iApprove','dApprove','cApprove','vRemark','cCreated','dCreated','cUpdated','dUpdated'); 
        $grid->setGridView('grid');


        switch ($action) {
            case 'json':
                    $grid->getJsonData();
                    break;
            case 'view':
                    $grid->render_form($this->input->get('id'), true);
                    break;

             case 'create':
                    $grid->render_form();
                    break;
             
                case 'createproses':
                    echo $grid->saved_form();
                    break;
                  
           
            
            case 'update':
                    $grid->render_form($this->input->get('id'));
                    break;

        
            case 'updateproses':
                    echo $grid->updated_form();
                    break;
        
        
            case 'delete':
                    echo $grid->delete_row();
                    break; 
            /*
                //Ini Merupakan Standart Case Untuk Approve

                case 'approve':
                    echo $this->approve_view();
                    break;
                case 'approve_process':
                    echo $this->approve_process();
                    break;
                case 'reject':
                    echo $this->reject_view();
                    break;
                case 'reject_process':
                    echo $this->reject_process();
                    break;

                
            */ 
                case 'download':
                    $this->download($this->input->get('file'));
                    break;
            default:
                    $grid->render_grid();
                    break;
        }
    }



    //Jika Ingin Menambahkan Seting grid seperti button edit enable dalam kondisi tertentu
    /* 
    function listBox_Action($row, $actions) {
        if ($row->vNo_Or<>'' || $row->vNo_Or<>NULL) { 
                unset($actions['edit']);
        }
        return $actions;
    } 
    */

                        function insertBox_mt01_vNo_transaksi($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30"  />';
                            $return .= '<input type="hidden" name="isdraft"    class="input_rows1 " size="30"  />';
                            return $return;
                        }
                        
                        function updateBox_mt01_vNo_transaksi($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1  required" size="30" value="'.$value.'"/>';
                                    $return .= '<input type="hidden" name="isdraft"   class="input_rows1 " size="30"  />';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt01_vNomor($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30"  />';
                            return $return;
                        }
                        
                        function updateBox_mt01_vNomor($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1  required" size="30" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt01_vLampiran($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30"  />';
                            return $return;
                        }
                        
                        function updateBox_mt01_vLampiran($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1  required" size="30" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt01_vPerihal($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30"  />';
                            return $return;
                        }
                        
                        function updateBox_mt01_vPerihal($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1  required" size="30" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt01_dTanggal($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 tanggal required" size="8" />';
                            return $return;
                        }
                        
                        function updateBox_mt01_dTanggal($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 tanggal  required" size="8" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt01_iCustomer($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30"  />';
                            return $return;
                        }
                        
                        function updateBox_mt01_iCustomer($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1  required" size="30" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt01_vNama_produsen($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30"  />';
                            return $return;
                        }
                        
                        function updateBox_mt01_vNama_produsen($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1  required" size="30" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt01_vAlamat_produsen($field, $id) {
                            $return = '<textarea name="'.$field.'" id="'.$id.'" class="required" style="width: 240px; height: 75px;" size="250" maxlength ="250"></textarea>';
                            return $return;
                        }
                        
                        function updateBox_mt01_vAlamat_produsen($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= '<label title="Note">'.nl2br($value).'</label>'; 
                                }else{ 
                                    $return = '<textarea name="'.$field.'" id="'.$id.'" class="required" style="width: 240px; height: 75px;" size="250" maxlength ="250">'.nl2br($value).'</textarea>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt01_iM_tujuan_pengujian($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" />';
                            return $return;
                        }
                        
                        function updateBox_mt01_iM_tujuan_pengujian($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt01_vTujuan_pengujian_ket($field, $id) {
                            $return = '<textarea name="'.$field.'" id="'.$id.'" class="required" style="width: 240px; height: 75px;" size="250" maxlength ="250"></textarea>';
                            return $return;
                        }
                        
                        function updateBox_mt01_vTujuan_pengujian_ket($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= '<label title="Note">'.nl2br($value).'</label>'; 
                                }else{ 
                                    $return = '<textarea name="'.$field.'" id="'.$id.'" class="required" style="width: 240px; height: 75px;" size="250" maxlength ="250">'.nl2br($value).'</textarea>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt01_vNama_sample($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30"  />';
                            return $return;
                        }
                        
                        function updateBox_mt01_vNama_sample($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1  required" size="30" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt01_iM_jenis_sediaan($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" />';
                            return $return;
                        }
                        
                        function updateBox_mt01_iM_jenis_sediaan($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt01_iSudah_beredar($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" />';
                            return $return;
                        }
                        
                        function updateBox_mt01_iSudah_beredar($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt01_vZat_aktif($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30"  />';
                            return $return;
                        }
                        
                        function updateBox_mt01_vZat_aktif($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1  required" size="30" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt01_vBatch_lot($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30"  />';
                            return $return;
                        }
                        
                        function updateBox_mt01_vBatch_lot($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1  required" size="30" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt01_dTgl_produksi($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 tanggal required" size="8" />';
                            return $return;
                        }
                        
                        function updateBox_mt01_dTgl_produksi($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 tanggal  required" size="8" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt01_dTgl_kadaluarsa($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 tanggal required" size="8" />';
                            return $return;
                        }
                        
                        function updateBox_mt01_dTgl_kadaluarsa($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 tanggal  required" size="8" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt01_vNo_registrasi($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30"  />';
                            return $return;
                        }
                        
                        function updateBox_mt01_vNo_registrasi($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1  required" size="30" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt01_vKemasan($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30"  />';
                            return $return;
                        }
                        
                        function updateBox_mt01_vKemasan($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1  required" size="30" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt01_iJumlah_diserahkan($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" />';
                            return $return;
                        }
                        
                        function updateBox_mt01_iJumlah_diserahkan($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt01_vSuhu_penyimpanan($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30"  />';
                            return $return;
                        }
                        
                        function updateBox_mt01_vSuhu_penyimpanan($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1  required" size="30" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt01_vPermohonan_lampiran($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30"  />';
                            return $return;
                        }
                        
                        function updateBox_mt01_vPermohonan_lampiran($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1  required" size="30" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt01_dTgl_ambil_sample($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 tanggal required" size="8" />';
                            return $return;
                        }
                        
                        function updateBox_mt01_dTgl_ambil_sample($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 tanggal  required" size="8" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt01_dTgl_serah_sample($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 tanggal required" size="8" />';
                            return $return;
                        }
                        
                        function updateBox_mt01_dTgl_serah_sample($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 tanggal  required" size="8" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt01_vPimpinan_perusahaan($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30"  />';
                            return $return;
                        }
                        
                        function updateBox_mt01_vPimpinan_perusahaan($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1  required" size="30" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt01_iSubmit($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" />';
                            return $return;
                        }
                        
                        function updateBox_mt01_iSubmit($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_mt01_iApprove($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" />';
                            return $return;
                        }
                        
                        function updateBox_mt01_iApprove($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
    /*
        //Ini Merupakan Standart Approve yang digunakan di erp
        function approve_view() {
            $echo = '<script type="text/javascript">
                         function submit_ajax(form_id) {
                            return $.ajax({
                                url: $("#"+form_id).attr("action"),
                                type: $("#"+form_id).attr("method"),
                                data: $("#"+form_id).serialize(),
                                success: function(data) {
                                    var o = $.parseJSON(data);
                                    var last_id = o.last_id;
                                    var url = "'.base_url().'processor/pengujian/mt01";                             
                                    if(o.status == true) { 
                                        $("#alert_dialog_form").dialog("close");
                                             $.get(url+"?action=update&id="+last_id, function(data) {
                                             $("div#form_mt01").html(data);
                                             
                                        });
                                        
                                    }
                                        reload_grid("grid_mt01");
                                }
                                
                             })
                         }
                     </script>';
            $echo .= '<h1>Approve</h1><br />';
            $echo .= '<form id="form_mt01_approve" action="'.base_url().'processor/pengujian/mt01?action=approve_process" method="post">';
            $echo .= '<div style="vertical-align: top;">';
            $echo .= 'Remark : 
                    <input type="hidden" name="iMt01" value="'.$this->input->get('iMt01').'" />
                    <input type="hidden" name="modul_id" value="'.$this->input->get('modul_id').'" />
                    <input type="hidden" name="lvl" value="'.$this->input->get('lvl').'" />
                    <input type="hidden" name="group_id" value="'.$this->input->get('group_id').'" />
                    
                    <textarea name="vRemark"></textarea>
            <button type="button" onclick="submit_ajax(\'form_mt01_approve\')">Approve</button>';
                
            $echo .= '</div>';
            $echo .= '</form>';
            return $echo;
        } 

        function approve_process() {
            $post = $this->input->post();
            $cNip= $this->user->gNIP;
            $vName= $this->user->gName;
            $iMt01 = $post['iMt01'];
            $vRemark = $post['vRemark'];
            $lvl = $post['lvl'];

            //Letakan Query Update approve disini

            $data['status']  = true;
            $data['last_id'] = $post['iMt01'];
            return json_encode($data);
        }
    */


    /*
        //Ini Merupakan Standart Reject yang digunakan di erp
        function reject_view() {
            $echo = '<script type="text/javascript">
                         function submit_ajax(form_id) {
                            var remark = $("#mt01_remark").val();
                            if (remark=="") {
                                alert("Remark tidak boleh kosong ");
                                return
                            }

                            return $.ajax({
                                url: $("#"+form_id).attr("action"),
                                type: $("#"+form_id).attr("method"),
                                data: $("#"+form_id).serialize(),
                                success: function(data) {
                                    var o = $.parseJSON(data);
                                    var last_id = o.last_id;
                                    var url = "'.base_url().'processor/pengujian/mt01";                             
                                    if(o.status == true) { 
                                        $("#alert_dialog_form").dialog("close");
                                             $.get(url+"?action=update&id="+last_id, function(data) {
                                             $("div#form_mt01").html(data);
                                             
                                        });
                                        
                                    }
                                        reload_grid("grid_mt01");
                                }
                                
                             })
                         }
                     </script>';
            $echo .= '<h1>Reject</h1><br />';
            $echo .= '<form id="form_mt01_reject" action="'.base_url().'processor/pengujian/mt01?action=reject_process" method="post">';
            $echo .= '<div style="vertical-align: top;">';
            $echo .= 'Remark : 
                    <input type="hidden" name="iMt01" value="'.$this->input->get('iMt01').'" />
                    <input type="hidden" name="modul_id" value="'.$this->input->get('modul_id').'" />
                    <input type="hidden" name="lvl" value="'.$this->input->get('lvl').'" />
                    <input type="hidden" name="group_id" value="'.$this->input->get('group_id').'" />
                    
                    <textarea name="vRemark" id="reject_mt01_remark"></textarea>
            <button type="button" onclick="submit_ajax(\'form_mt01_reject\')">Reject</button>';
                
            $echo .= '</div>';
            $echo .= '</form>';
            return $echo;
        }


        
        function reject_process() {
            $post = $this->input->post();
            $cNip= $this->user->gNIP;
            $vName= $this->user->gName;
            $iMt01 = $post['iMt01'];
            $vRemark = $post['vRemark'];
            $lvl = $post['lvl'];

            //Letakan Query Update approve disini

            $data['status']  = true;
            $data['last_id'] = $post['iMt01'];
            return json_encode($data);
        }
    */


    //Standart Setiap table harus memiliki dCreated , cCreated, dUpdated, cUpdated
    function before_insert_processor($row, $postData) {
        $postData['dCreated'] = date('Y-m-d H:i:s');
        $postData['cCreated']=$this->user->gNIP;


        if($postData['isdraft']==true){
            $postData['iSubmit']=0;
        } else{
            $postData['iSubmit']=1;
        } 


        return $postData;

    }
    function before_update_processor($row, $postData) {
        $postData['dUpdated'] = date('Y-m-d H:i:s');
        $postData['cUpdated'] = $this->user->gNIP;

        if($postData['isdraft']==true){
            $postData['iSubmit']=0;
        } else{
            $postData['iSubmit']=1;
        } 


        return $postData; 
    }    

    function after_insert_processor($fields, $id, $postData) {
        //Example After Insert
        /*
        $cNip = $this->sess_auth->gNIP; 
        $sql = 'Place Query In Here';
        $this->dbset->query($sql);
        */
    }

    function after_update_processor($fields, $id, $postData) {
        //Example After Update
        /*
        $cNip = $this->sess_auth->gNIP; 
        $sql = 'Place Query In Here';
        $this->dbset->query($sql);
        */
    }

    function manipulate_insert_button($buttons) { 
        //Load Javascript In Here 
        $cNip= $this->user->gNIP;
        $js = $this->load->view('js/standard_js');
        $js .= $this->load->view('js/upload_js');

        $iframe = '<iframe name="mt01_frame" id="mt01_frame" height="0" width="0"></iframe>';
        
        $save_draft = '<button onclick="javascript:save_draft_btn_multiupload(\'mt01\', \' '.base_url().'processor/pengujian/mt01?draft=true \',this,true )"  id="button_save_draft_mt01"  class="ui-button-text icon-save" >Save as Draft</button>';
        $save = '<button onclick="javascript:save_btn_multiupload(\'mt01\', \' '.base_url().'processor/pengujian/mt01?company_id='.$this->input->get('company_id').'&group_id='.$this->input->get('group_id').'modul_id='.$this->input->get('modul_id').' \',this,true )"  id="button_save_submit_mt01"  class="ui-button-text icon-save" >Save &amp; Submit</button>';

        

        $buttons['save'] = $iframe.$save_draft.$save.$js;
        
        return $buttons;
    }

    function manipulate_update_button($buttons, $rowData) { 
        $peka=$rowData['iMt01'];


        //Load Javascript In Here 
        $cNip= $this->user->gNIP;
        $js = $this->load->view('js/standard_js');
        $js .= $this->load->view('js/upload_js');

        $iframe = '<iframe name="mt01_frame" id="mt01_frame" height="0" width="0"></iframe>';
        
        $update_draft = '<button onclick="javascript:update_draft_btn(\'mt01\', \' '.base_url().'processor/pengujian/mt01?draft=true \',this,true )"  id="button_update_draft_mt01"  class="ui-button-text icon-save" >Update as Draft</button>';
        $update = '<button onclick="javascript:update_btn_back(\'mt01\', \' '.base_url().'processor/pengujian/mt01?company_id='.$this->input->get('company_id').'&group_id='.$this->input->get('group_id').'modul_id='.$this->input->get('modul_id').' \',this,true )"  id="button_update_submit_mt01"  class="ui-button-text icon-save" >Update &amp; Submit</button>';

        $approve = '<button onclick="javascript:load_popup(\' '.base_url().'processor/pengujian/mt01?action=approve&iMt01='.$peka.'&company_id='.$this->input->get('company_id').'&group_id='.$this->input->get('group_id').'&modul_id='.$this->input->get('modul_id').' \')"  id="button_approve_mt01"  class="ui-button-text icon-save" >Approve</button>';
        $reject = '<button onclick="javascript:load_popup(\' '.base_url().'processor/pengujian/mt01?action=reject&iMt01='.$peka.'&company_id='.$this->input->get('company_id').'&group_id='.$this->input->get('group_id').'&modul_id='.$this->input->get('modul_id').' \' )"  id="button_reject_mt01"  class="ui-button-text icon-save" >Reject</button>';
        



        if ($this->input->get('action') == 'view') {
            unset($buttons['update']);
        }
        else{ 
            $buttons['update'] = $iframe.$update_draft.$update.$js;    
        }
        
        return $buttons;
    }

    function whoAmI($nip) { 
        $sql = 'select b.vDescription as vdepartemen,a.*,b.*,c.iLvlemp 
                        from hrd.employee a 
                        join hrd.msdepartement b on b.iDeptID=a.iDepartementID
                        join hrd.position c on c.iPostId=a.iPostID
                        where a.cNip ="'.$nip.'"
                        ';
        
        $data = $this->dbset->query($sql)->row_array();
        return $data;
    }

    function download($vFilename) { 
        $this->load->helper('download');        
        $name = $vFilename;
        $id = $_GET['id'];
        $tempat = $_GET['path'];    
        $path = file_get_contents('./files/pengujian/'.$tempat.'/'.$id.'/'.$name);    
        force_download($name, $path);


    }

    //Output
    public function output(){
        $this->index($this->input->get('action'));
    }

}
