 
<?php
/* Generated by Softdev 2 ERP Module Generator 2019-04-01 00:31:21 */
/* Location: ./modules/pengujian/controllers/sertifikat.php */
/* Please DO NOT modify this information : */ 


/*
    Preparation 
    1. untuk load view halaman upload , file berada pada folder partial;
    2. lib auth untuk fungsi check modul



    Parameter need to be change after generate 
    1. FOLDER_APP => change to folder name where this controllers should be there
    2. Static Dropdown => change value for option
    3. Dynamic Dropdown => Change query for option

    Table Sample 
    test.item && test.item_file_upload




*/
 


 
if ( ! defined('BASEPATH')) exit('No direct script access allowed');
class sertifikat extends MX_Controller {
	var $masterUrl;
    function __construct() {
        parent::__construct();
         $this->load->library('auth');
        $this->db = $this->load->database('hrd',false, true);
        $this->user = $this->auth->user();

        $this->title = 'Sertifikat';
        $this->url = 'sertifikat';
        $this->urlpath = 'pengujian/'.str_replace("_","/", $this->url);

		$this->report    = $this->load->library('report');
		$url             = $_SERVER['HTTP_REFERER'];
		$company_id      = substr($url, strrpos($url, '/') + 1);
		$this->masterUrl = base_url()."processor/pengujian/sertifikat?company_id={$this->input->get('company_id')}";


        $this->maintable = 'bbpmsoh.mt01';  
        $this->main_table = $this->maintable;   
        $this->main_table_pk = 'iMt01'; 
        $datagrid['islist'] = array(
            'vNo_transaksi' => array('label'=>'No Transaksi','width'=>100,'align'=>'center','search'=>true)
            ,'vNomor' => array('label'=>'Nomor','width'=>100,'align'=>'center','search'=>true)
            ,'vNama_produsen' => array('label'=>'Nama Produsen','width'=>300,'align'=>'left','search'=>true)
            ,'iSubmit_sertifikat' => array('label'=>'Submit','width'=>100,'align'=>'center','search'=>true)
            ,'iStatus_sertifikat' => array('label'=>'Status Sertifikat','width'=>200,'align'=>'center','search'=>true)
            ,'iSphu_app' => array('label'=>'Status Bagian SPHU','width'=>200,'align'=>'center','search'=>true)
            ,'iTu_app' => array('label'=>'Status Bagian TU','width'=>200,'align'=>'center','search'=>true)
            ,'iFa_app' => array('label'=>'Status Bagian Keuangan','width'=>200,'align'=>'center','search'=>true)
        );

        $datagrid['jointableinner']=array(
            0=>array('bbpmsoh.mt06'=>'mt06.iMt01=bbpmsoh.mt01.iMt01')
            );

        $datagrid['addFields']=array(
        		'iStatus_sertifikat' => 'Status Sertifikat'
        		,'vNo_transaksi' => 'No Transaksi'
        		,'vNomor' => 'Nomor'
        		,'vLampiran' => 'Lampiran'
        		,'vPerihal' => 'Perihal'
        		,'dTanggal' => 'Tanggal'
        		,'iCustomer' => 'Customer'
                );
        $datagrid['isRequired']=array('all_form');
        $datagrid['shortBy']=array('mt01.dUpdated'=>'Desc');
    
        $datagrid['setQuery']=array(
                                0=>array('vall'=>'mt01.lDeleted','nilai'=>0)
                                );
        
        $this->datagrid=$datagrid;
    }

    function index($action = '') {
        $grid = new Grid;       
        $grid->setTitle($this->title);      
        $grid->setTable($this->maintable );
        $grid->setUrl($this->url);

        /*Untuk Field*/
        foreach ($this->datagrid as $kv => $vv) {
            /*Untuk List*/
            if($kv=='islist'){
                foreach ($vv as $list => $vlist) {
                    $grid->addList($list);
                    foreach ($vlist as $kdis => $vdis) {
                        if($kdis=='label'){
                            $grid->setLabel($list, $vdis);
                        }
                        if($kdis=='width'){
                            $grid->setWidth($list, $vdis);
                        }
                        if($kdis=='align'){
                            $grid->setAlign($list, $vdis);
                        }
                        if($kdis=='search' && $vdis==true){
                            $grid->setSearch($list);
                        }
                    }
                }
            }

            /*Untuk Short List*/
            if($kv=='shortBy'){
                foreach ($vv as $list => $vlist) {
                    $grid->setSortBy($list);
                    $grid->setSortOrder($vlist);
                }
            }

            if($kv=='addFields'){
                foreach ($vv as $list => $vlist) {
                    $grid->addFields($list);
                    $grid->setLabel($list, $vlist);
                }
            }

            if($kv=='inputGet'){
                foreach ($vv as $list => $vlist) {
                    $grid->setInputGet($list,$vlist);
                }
            }

            if($kv=='jointableinner'){
                foreach ($vv as $list => $vlist) {
                    foreach ($vlist as $tbjoin => $onjoin) {
                        $grid->setJoinTable($tbjoin, $onjoin, 'inner');
                    }
                }
            }
            if($kv=='setQuery'){
                foreach ($vv as $list => $vlist) {
                    $grid->setQuery($vlist['vall'], $vlist['nilai']);
                }
            }
            if($kv=='isRequired'){
                foreach ($vv as $list => $vlist) {
                    if($vlist=="all_form"){
                        foreach ($this->datagrid['addFields'] as $kfield => $vfield) {
                            $grid->setRequired($kfield);
                        }
                    }
                }
            }

        }

        //$groupnya = $this->checkgroup($this->user->gNIP);             
        //if( $groupnya['idprivi_group']== 7){
        //    $grid->setQuery('mt01.iCustomer',$this->user->gNIP );     
        //}


        $grid->changeFieldType('iSubmit_sertifikat', 'combobox','',array(''=>'--select--', 0=>'Draft', 1=>'Submit'));
        $grid->changeFieldType('iStatus_sertifikat', 'combobox','',array(''=>'', 1=>'Tidak Memenuhi Syarat', 2=>'Memenuhi Syarat'));
        $grid->changeFieldType('iType_pemohon', 'combobox','',array(''=>'--select--', 1=>'Perorangan', 2=>'Perusahaan', 3=>'Dinas'));
        $grid->changeFieldType('iSudah_beredar', 'combobox','',array(''=>'--select--', 0=>'Belum', 2=>'Sudah'));

        $grid->changeFieldType('iSphu_app', 'combobox','',array(''=>'Pilih','0'=>'Need Approval', 1=>'Reject', 2=>'Approved'));
        $grid->changeFieldType('iTu_app', 'combobox','',array(''=>'Pilih','0'=>'Need Approval', 1=>'Reject', 2=>'Approved'));
        $grid->changeFieldType('iFa_app', 'combobox','',array(''=>'Pilih','0'=>'Need Approval', 1=>'Reject', 2=>'Approved'));
        
    //set required
        $grid->setRequired('vNo_transaksi','vNomor','vLampiran','vPerihal','dTanggal','iCustomer','iType_pemohon','vNama_produsen','vAlamat_produsen','iM_tujuan_pengujian','vTujuan_pengujian_ket','vNama_sample','iM_jenis_sediaan','vJenis_sediaan_ket','iSudah_beredar','vZat_aktif','vBatch_lot','dTgl_produksi','dTgl_kadaluarsa','vNo_registrasi','vKemasan','iJumlah_diserahkan','vSuhu_penyimpanan','vPermohonan_lampiran','dTgl_ambil_sample','dTgl_serah_sample','vPimpinan_perusahaan'); 

        $grid->setRelation('iM_tujuan_pengujian','bbpmsoh.m_tujuan_pengujian','iM_tujuan_pengujian','vNama_tujuan','','inner',array('lDeleted'=>0),array('cKode'=>'asc'));
        $grid->setRelation('iM_jenis_sediaan','bbpmsoh.m_jenis_sediaan','iM_jenis_sediaan','vJenis_sediaan','','inner',array('lDeleted'=>0),array('vJenis_sediaan'=>'asc'));


        $groupnya = $this->checkgroup($this->user->gNIP);             
        if( $groupnya['idprivi_group'] == 2){
            // syaratnya pengujian semuanya beres
            //$grid->setQuery('iSubmit_sertifikat in (0)',NULL);

            $grid->setQuery('IF( (select a.iDist_virologi 
                                            from bbpmsoh.mt06 a
                                            where a.lDeleted=0 
                                            and  a.iMt01= `mt01`.iMt01 ) = 1 ,
                                                 `mt01`.iMt01 in  (select a.iMt01 
                                                                                        from bbpmsoh.mt08a a
                                                                                        where a.lDeleted=0 
                                                                                        and  a.iApprove_qa=2  ) 
                                                                                        
                            ,`mt01`.`lDeleted` =  0
                            )',NULL);  

            $grid->setQuery('IF( (select a.iDist_bakteri 
                                            from bbpmsoh.mt06 a
                                            where a.lDeleted=0 
                                            and  a.iMt01= `mt01`.iMt01 ) = 1 ,
                                                 `mt01`.iMt01 in  (select a.iMt01 
                                                                                        from bbpmsoh.mt08b a
                                                                                        where a.lDeleted=0 
                                                                                        and  a.iApprove_qa=2  ) 
                                                                                        
                            ,`mt01`.`lDeleted` =  0
                            )',NULL);  

            $grid->setQuery('IF( (select a.iDist_farmastetik 
                                            from bbpmsoh.mt06 a
                                            where a.lDeleted=0 
                                            and  a.iMt01= `mt01`.iMt01 ) = 1 ,
                                                 `mt01`.iMt01 in  (select a.iMt01 
                                                                                        from bbpmsoh.mt09 a
                                                                                        where a.lDeleted=0 
                                                                                        and  a.iApprove_qa=2  ) 
                                                                                        
                            ,`mt01`.`lDeleted` =  0
                            )',NULL);   



            if($dMt06['iDist_virologi']==1 or $dMt06['iDist_bakteri']==1 ){
                // biologik
                $templatenya = 'sertifikatB.docx';

            }else{
                // farmastetik
                $templatenya = 'sertifikatF.docx';
            }


        }else if($groupnya['idprivi_group'] == 6){

        	$grid->setQuery('iStatus_sertifikat',2);

        }else if($groupnya['idprivi_group'] == 9){
        	$grid->setQuery('iSphu_app',2);

        }else if($groupnya['idprivi_group'] == 10){
        	$grid->setQuery('iTu_app',2);

        }


        $grid->setGridView('grid');


        switch ($action) {
            case 'json':
                    $grid->getJsonData();
                    break;
            case 'view':
                    $grid->render_form($this->input->get('id'), true);
                    break;

             case 'create':
                    $grid->render_form();
                    break;
             
                case 'createproses':
                    echo $grid->saved_form();
                    break;
                  
           
            
            case 'update':
                    $grid->render_form($this->input->get('id'));
                    break;

        
            case 'updateproses':
                    echo $grid->updated_form();
                    break;
        
        
            case 'delete':
                    echo $grid->delete_row();
                    break; 
            
                //Ini Merupakan Standart Case Untuk Approve

                case 'approve':
                    echo $this->approve_view();
                    break;
                case 'approve_process':
                    echo $this->approve_process();
                    break;
                case 'reject':
                    echo $this->reject_view();
                    break;
                case 'reject_process':
                    echo $this->reject_process();
                    break;

                case 'getDataMemo':
					echo $this->getDataMemo();
				break;
                
            
                case 'download':
                    $this->download($this->input->get('file'));
                    break;
            default:
                    $grid->render_grid();
                    break;
        }
    }


    function getDataMemo() {
		$id   = $this->input->post('id');
		$data = array();

    	$sql = "select * 
    			from bbpmsoh.mt01 a
    			join hrd.employee b on cNip=a.iCustomer
    			join bbpmsoh.m_jenis_sediaan c on c.iM_jenis_sediaan=a.iM_jenis_sediaan
    			WHERE a.iMt01 = '{$id}'";

    			
    	$query = $this->db->query($sql);

    	foreach ($query->result() as $row) {
    		
			$row_array['NAMA_PEMOHON']      = ucwords(strtolower($row->vName));
			$row_array['ALAMAT_PEMOHON']      = ucwords(strtolower($row->vAddress));
			$row_array['NAMA_PRODUSEN']      = ucwords(strtolower($row->vNama_produsen));
			$row_array['ALAMAT_PRODUSEN']      = ucwords(strtolower($row->vAlamat_produsen));
			$row_array['KADALUARSA']      = ucwords(strtolower($row->dTgl_kadaluarsa));
			$row_array['NOREG']      = ucwords(strtolower($row->vNo_registrasi));
			$row_array['KEMASAN']      = ucwords(strtolower($row->vKemasan));
			$row_array['JENIS']      = ucwords(strtolower($row->vJenis_sediaan));
			$row_array['NOMOR_UJI']      = ucwords(strtolower($row->vNomor));
			

			array_push($data, $row_array);
    	}

    	echo json_encode($data);
    }


    function checkgroup($nip){
        $sql = "select *,a.idprivi_group,a.vNamaGroup 
                from erp_privi.privi_group_pt_app a 
                join erp_privi.privi_apps b on b.idprivi_apps=a.idprivi_apps
                join erp_privi.privi_authlist c on c.idprivi_apps=b.idprivi_apps and c.idprivi_group=a.iID_GroupApp
                where 
                b.idprivi_apps=130
                and 
                c.cNIP='".$nip."' ";
        $ret = $this->db->query($sql)->row_array();
        return $ret;
    }




    //Jika Ingin Menambahkan Seting grid seperti button edit enable dalam kondisi tertentu
    /* 
    function listBox_Action($row, $actions) {
        if ($row->vNo_Or<>'' || $row->vNo_Or<>NULL) { 
                unset($actions['edit']);
        }
        return $actions;
    } 
    */

                        function insertBox_sertifikat_vNo_transaksi($field, $id) {
                            $return = 'Auto Generated';
                            $return .= '<input type="hidden" name="isdraft"    class="input_rows1 " size="30"  />';
                            return $return;
                        }
                        
                        function updateBox_sertifikat_vNo_transaksi($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="hidden" name="'.$field.'"  id="'.$id.'"  class="input_rows1 tanggal  required" size="8" value="'.$value.'"/>';
                                    $return .= '<input type="hidden" name="isdraft"    class="input_rows1 " size="30"  />';
                                    $return .= $value;


                                }
                                
                            return $return;
                        }
                        
                        function insertBox_sertifikat_vNomor($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30"  />';
                            return $return;
                        }
                        
                        function updateBox_sertifikat_vNomor($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="hidden" name="'.$field.'"  id="'.$id.'"  class="input_rows1 tanggal  required" size="8" value="'.$value.'"/>';
                                    $return .= $value;

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_sertifikat_vLampiran($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30"  />';
                            return $return;
                        }
                        
                        function updateBox_sertifikat_vLampiran($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="hidden" name="'.$field.'"  id="'.$id.'"  class="input_rows1 tanggal  required" size="8" value="'.$value.'"/>';
                                    $return .= $value;

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_sertifikat_vPerihal($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30"  />';
                            return $return;
                        }
                        
                        function updateBox_sertifikat_vPerihal($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="hidden" name="'.$field.'"  id="'.$id.'"  class="input_rows1 tanggal  required" size="8" value="'.$value.'"/>';
                                    $return .= $value;

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_sertifikat_dTanggal($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 tanggal required" size="8" />';
                            return $return;
                        }
                        
                        function updateBox_sertifikat_dTanggal($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="hidden" name="'.$field.'"  id="'.$id.'"  class="input_rows1 tanggal  required" size="8" value="'.$value.'"/>';
                                    $return .= $value; 

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_sertifikat_iCustomer($field, $id) {
                            $groupnya = $this->checkgroup($this->user->gNIP);             
                           
                            if($groupnya['idprivi_group'] == 7){
                                 $this->db->select("*")
                                    ->from("hrd.employee")
                                    ->where("iDivisionID",7)
                                    ->where("cNip",$this->user->gNIP)
                                    ->where("iVerifikasi",1);
                            }else{
                                $this->db->select("*")
                                    ->from("hrd.employee")
                                    ->where("iDivisionID",7)
                                    ->where("iVerifikasi",1);
                            }
                            


                            $fo=$this->db->get()->result_array();
                            $return="<select id='".$id."' name='".$field."' class='required'>";
                            $return.="<option value=''>---Pilih---</option>";
                            foreach ($fo as $kf => $vvf) {
                                $return.="<option value='".$vvf['cNip']."'>".$vvf["vName_company"].' - '.$vvf["vName"]."</option>";
                            }
                            $return.="</select>";
                            return $return;
                        }
                        
                        function updateBox_sertifikat_iCustomer($field, $id, $value, $rowData) {
                           		$this->db->select("*")
                                        ->from("hrd.employee")
                                        ->where("cNip",$value);
                                $fo=$this->db->get()->row_array();
                            
                            $return = '<input type="hidden" name="'.$field.'"  id="'.$id.'"  class="input_rows1 tanggal  required" size="8" value="'.$value.'"/>';
                            $return .= $fo['vName'].' - '.$fo['vName_company'];

                            return $return;
                        }

                        function insertBox_sertifikat_iCustomer1($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30"  />';
                            return $return;
                        }
                        
                        function updateBox_sertifikat_iCustomer1($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1  required" size="30" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_sertifikat_vNama_produsen($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30"  />';
                            return $return;
                        }
                        
                        function updateBox_sertifikat_vNama_produsen($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1  required" size="30" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_sertifikat_vAlamat_produsen($field, $id) {
                            $return = '<textarea name="'.$field.'" id="'.$id.'" class="required" style="width: 240px; height: 75px;" size="250" maxlength ="250"></textarea>';
                            return $return;
                        }
                        
                        function updateBox_sertifikat_vAlamat_produsen($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= '<label title="Note">'.nl2br($value).'</label>'; 
                                }else{ 
                                    $return = '<textarea name="'.$field.'" id="'.$id.'" class="required" style="width: 240px; height: 75px;" size="250" maxlength ="250">'.nl2br($value).'</textarea>';

                                }
                                
                            return $return;
                        }
                        
                       /* function insertBox_sertifikat_iM_tujuan_pengujian($field, $id) {
                            $this->db->select("*")
                                    ->from("bbpmsoh.m_tujuan_pengujian")
                                    ->where("lDeleted",0);
                            $fo=$this->db->get()->result_array();
                            $return="<select id='".$id."' name='".$field."' class='required'>";
                            $return.="<option value=''>---Pilih---</option>";
                            foreach ($fo as $kf => $vvf) {
                                $return.="<option value='".$vvf['iM_tujuan_pengujian']."'>".$vvf["vNama_tujuan"]."</option>";
                            }
                            $return.="</select>";
                            return $return;
                        }
                        
                        function updateBox_sertifikat_iM_tujuan_pengujian($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }*/
                        
                        function insertBox_sertifikat_vTujuan_pengujian_ket($field, $id) {
                            $return = '<textarea name="'.$field.'" id="'.$id.'" class="required" style="width: 240px; height: 75px;" size="250" maxlength ="250"></textarea>';
                            return $return;
                        }
                        
                        function updateBox_sertifikat_vTujuan_pengujian_ket($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= '<label title="Note">'.nl2br($value).'</label>'; 
                                }else{ 
                                    $return = '<textarea name="'.$field.'" id="'.$id.'" class="required" style="width: 240px; height: 75px;" size="250" maxlength ="250">'.nl2br($value).'</textarea>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_sertifikat_vNama_sample($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30"  />';
                            return $return;
                        }
                        
                        function updateBox_sertifikat_vNama_sample($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1  required" size="30" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        /*function insertBox_sertifikat_iM_jenis_sediaan($field, $id) {
                             $this->db->select("*")
                                    ->from("bbpmsoh.m_jenis_sediaan")
                                    ->where("lDeleted",0);
                            $fo=$this->db->get()->result_array();
                            $return="<select id='".$id."' name='".$field."' class='required'>";
                            $return.="<option value=''>---Pilih---</option>";
                            foreach ($fo as $kf => $vvf) {
                                $return.="<option value='".$vvf['iM_jenis_sediaan']."'>".$vvf["vJenis_sediaan"]."</option>";
                            }
                            $return.="</select>";
                            return $return;
                        }
                        
                        function updateBox_sertifikat_iM_jenis_sediaan($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_sertifikat_iSudah_beredar($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" />';
                            return $return;
                        }
                        
                        function updateBox_sertifikat_iSudah_beredar($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }*/
                        
                        function insertBox_sertifikat_vZat_aktif($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30"  />';
                            return $return;
                        }
                        
                        function updateBox_sertifikat_vZat_aktif($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1  required" size="30" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_sertifikat_vBatch_lot($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30"  />';
                            return $return;
                        }
                        
                        function updateBox_sertifikat_vBatch_lot($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1  required" size="30" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_sertifikat_dTgl_produksi($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 tanggal required" size="8" />';
                            return $return;
                        }
                        
                        function updateBox_sertifikat_dTgl_produksi($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 tanggal  required" size="8" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_sertifikat_dTgl_kadaluarsa($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 tanggal required" size="8" />';
                            return $return;
                        }
                        
                        function updateBox_sertifikat_dTgl_kadaluarsa($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 tanggal  required" size="8" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_sertifikat_vNo_registrasi($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30"  />';
                            return $return;
                        }
                        
                        function updateBox_sertifikat_vNo_registrasi($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1  required" size="30" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_sertifikat_vKemasan($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30"  />';
                            return $return;
                        }
                        
                        function updateBox_sertifikat_vKemasan($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1  required" size="30" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_sertifikat_iJumlah_diserahkan($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" />';
                            return $return;
                        }
                        
                        function updateBox_sertifikat_iJumlah_diserahkan($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 angka required" size="10" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_sertifikat_vSuhu_penyimpanan($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30"  />';
                            return $return;
                        }
                        
                        function updateBox_sertifikat_vSuhu_penyimpanan($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1  required" size="30" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_sertifikat_vPermohonan_lampiran($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30"  />';
                            return $return;
                        }
                        
                        function updateBox_sertifikat_vPermohonan_lampiran($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1  required" size="30" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_sertifikat_dTgl_ambil_sample($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 tanggal required" size="8" />';
                            return $return;
                        }
                        
                        function updateBox_sertifikat_dTgl_ambil_sample($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 tanggal  required" size="8" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_sertifikat_dTgl_serah_sample($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 tanggal required" size="8" />';
                            return $return;
                        }
                        
                        function updateBox_sertifikat_dTgl_serah_sample($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 tanggal  required" size="8" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_sertifikat_vPimpinan_perusahaan($field, $id) {
                            $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1 required" size="30"  />';
                            return $return;
                        }
                        
                        function updateBox_sertifikat_vPimpinan_perusahaan($field, $id, $value, $rowData) {
                                if ($this->input->get('action') == 'view') {
                                     $return= $value; 
                                }else{ 
                                    $return = '<input type="text" name="'.$field.'"  id="'.$id.'"  class="input_rows1  required" size="30" value="'.$value.'"/>';

                                }
                                
                            return $return;
                        }
                        
                        function insertBox_sertifikat_iSubmit($field, $id) {
                            $return = '-';
                            return $return;
                        }
                        
                        function updateBox_sertifikat_iSubmit($field, $id, $value, $rowData) {
                            $arr=array(0=>"Draft",1=>"Submited");
                            $return=isset($arr[$value])?$arr[$value]:"-";                                
                            return $return;
                        }
                        
                        function insertBox_sertifikat_iApprove($field, $id) {
                            $return = '-';
                            return $return;
                        }
                        
                        function updateBox_sertifikat_iApprove($field, $id, $value, $rowData) {
                            $arr=array(0=>"Waiting Approval",1=>"Rejected",2=>"Approved");
                            $return=isset($arr[$value])?$arr[$value]:"-";                                
                            return $return;
                        }
                        
        //Ini Merupakan Standart Approve yang digunakan di erp
        function approve_view() {
            $echo = '<script type="text/javascript">
                         function submit_ajax(form_id) {
                            return $.ajax({
                                url: $("#"+form_id).attr("action"),
                                type: $("#"+form_id).attr("method"),
                                data: $("#"+form_id).serialize(),
                                success: function(data) {
                                    var o = $.parseJSON(data);
                                    var last_id = o.last_id;
                                    var url = "'.base_url().'processor/pengujian/sertifikat";                             
                                    if(o.status == true) { 
                                        $("#alert_dialog_form").dialog("close");
                                             $.get(url+"?action=update&id="+last_id, function(data) {
                                             $("div#form_sertifikat").html(data);
                                             
                                        });
                                        
                                    }
                                        reload_grid("grid_sertifikat");
                                }
                                
                             })
                         }
                     </script>';
            $echo .= '<h1>Approve</h1><br />';
            $echo .= '<form id="form_sertifikat_approve" action="'.base_url().'processor/pengujian/sertifikat?action=approve_process" method="post">';
            $echo .= '<div style="vertical-align: top;">';
            $echo .= 'Remark : 
                    <input type="hidden" name="iMt01" value="'.$this->input->get('iMt01').'" />
                    <input type="hidden" name="modul_id" value="'.$this->input->get('modul_id').'" />
                    <input type="hidden" name="level" value="'.$this->input->get('level').'" />
                    <input type="hidden" name="group_id" value="'.$this->input->get('group_id').'" />
                    
                    <textarea name="vRemark"></textarea>
            <button type="button" onclick="submit_ajax(\'form_sertifikat_approve\')">Approve</button>';
                
            $echo .= '</div>';
            $echo .= '</form>';
            return $echo;
        } 

        function approve_process() {
            $post = $this->input->post();
            $cNip= $this->user->gNIP;
            $vName= $this->user->gName;
            $iMt01 = $post['iMt01'];
            $vRemark = $post['vRemark'];
            $lvl = $post['level'];

            $qsql="
                        select * 
                        from bbpmsoh.mt01 a 
                        join hrd.employee b on b.cNip=a.iCustomer
                        join bbpmsoh.m_tujuan_pengujian c on c.iM_tujuan_pengujian=a.iM_tujuan_pengujian
                        where a.lDeleted=0 
                        and a.iMt01 = '".$iMt01."'

                ";
            $rsql = $this->db->query($qsql)->row_array();

            $subject = '';
            //Letakan Query Update approve disini
            if($lvl==1){
            	$dataupdate['cSphu_app']= $this->user->gNIP;
		        $dataupdate['dSphu_app']= date('Y-m-d H:i:s');
		        $dataupdate['vSphu_app']= $post['vRemark'];
		        $dataupdate['iSphu_app']= 2;

                $subject = 'e-Pengujian -> Approve SPHU Sertifikat '.$rsql['vNo_transaksi'];
                $precontent = 'Admin SPHU telah melakukan Approval Permintaan Permohonan Kontrak Pengujian Mutu Obat Hewan baru';
                $to = '0';


            }else if($lvl==2){
            	$dataupdate['cTu_app']= $this->user->gNIP;
		        $dataupdate['dTu_app']= date('Y-m-d H:i:s');
		        $dataupdate['vTu_app']= $post['vRemark'];
		        $dataupdate['iTu_app']= 2;

                $to = $rsql['iCustomer'] ;                        
                $subject = 'e-Pengujian -> Approve TU Sertifikat '.$rsql['vNo_transaksi'];
                $precontent = 'Admin TU telah melakukan Approval Permintaan Permohonan Kontrak Pengujian Mutu Obat Hewan baru';
                

            }else{
            	$dataupdate['cFa_app']= $this->user->gNIP;
		        $dataupdate['dFa_app']= date('Y-m-d H:i:s');
		        $dataupdate['vFa_app']= $post['vRemark'];
		        $dataupdate['iFa_app']= 2;

                $to = $rsql['iCustomer'] ;                        
                $subject = 'e-Pengujian -> Confirm Admin Keuangan Sertifikat '.$rsql['vNo_transaksi'];
                $precontent = 'Admin Keuangan telah melakukan Konfirmasi Permintaan Permohonan Kontrak Pengujian Mutu Obat Hewan baru';
            }
	        
	        $updet = $this->db->where('iMt01',$post['iMt01'])->update('bbpmsoh.mt01',$dataupdate);

            if($updet){

                if($subject <> ""){
                    $qsql="
                            select * 
                            from bbpmsoh.mt01 a 
                            join hrd.employee b on b.cNip=a.iCustomer
                            join bbpmsoh.m_tujuan_pengujian c on c.iM_tujuan_pengujian=a.iM_tujuan_pengujian
                            where a.lDeleted=0 
                            and a.iMt01 = '".$iMt01."'

                    ";
                    $rsql = $this->db->query($qsql)->row_array();

                    $iAm = $this->whoAmI($this->user->gNIP);

                    
                    $cc = $iAm['cNip'] ;

                    $sqlEmpAr = 'select * from bbpmsoh.sysparam a where a.vVariable="MAIL_SERTIFIKAT_APP"';
                    $dEmpAr =  $this->db->query($sqlEmpAr)->row_array();
                    $sq= $dEmpAr['vContent'];
                    $dataTO = $this->db->query($sq)->result_array();

                    
                    foreach ($dataTO as $toto) {
                        $to .=','.$toto['cNIP'];
                    }

                    $bccMail = 'select * from bbpmsoh.sysparam a where a.vVariable="MAIL_BCC"';
                    $dBcc =  $this->db->query($bccMail)->row_array();

                    $to = $to;
                    $cc = $this->user->gNIP.','.$dBcc['vContent'];

                    
                    $content="
                            <p>Diberitahukan bahwa ".$precontent." yang membutuhkan Follow up, dengan rincian sebagai berikut : <p>
                            <br><br>  
                            <table border='1' style='width: 750px;border-collapse: collapse;'>
                                <tr>
                                        <td style='width: 30%;'><b>Nomor Transaksi</b></td>
                                        <td> : ".$rsql['vNo_transaksi']."</td>
                                </tr>

                                <tr>
                                        <td style='width: 30%;'><b>Nama Pemohon</b></td>
                                        <td> : ".$rsql['cNip'].' || '.$rsql['vName']."</td>
                                </tr>


                                <tr>
                                        <td><b>No Permintaan</b></td>
                                        <td> : ".$rsql['vNomor']."</td>
                                </tr> 
                                <tr>
                                        <td><b>Perihal</b></td>
                                        <td> :".$rsql['vPerihal']."</td>
                                </tr> 

                                <tr>
                                        <td><b>Nama Perusahaan</b></td>
                                        <td> :".$rsql['vName_company']."</td>
                                </tr> 

                                <tr>
                                        <td><b>Alamat</b></td>
                                        <td> : ".nl2br($rsql['vAddress_company'])."</td>
                                </tr>

                                <tr>
                                        <td><b>Nama Produsen</b></td>
                                        <td> :".$rsql['vNama_produsen']."</td>
                                </tr> 

                                <tr>
                                        <td><b>Alamat Produsen</b></td>
                                        <td> : ".nl2br($rsql['vAlamat_produsen'])."</td>
                                </tr>

                                <tr>
                                        <td><b>Tujuan Pengujian Mutu</b></td>
                                        <td> : ".$rsql['vNama_tujuan']."</td>
                                </tr>

                                <tr>
                                        <td><b>Nama Sample</b></td>
                                        <td> : ".$rsql['vNama_sample']."</td>
                                </tr>  
                                <tr>
                                        <td><b>Status</b></td>
                                        <td> : Approve</td>
                                </tr>

                                <tr>
                                        <td><b>Lokasi Modul</b></td>
                                        <td> e-Pengujian -> Transaksi -> Sertifikat</td>
                                </tr>
                                
                            </table> 

                        <br/> <br/>
                        Demikian, mohon segera follow up  pada aplikasi e-Pengujian. Terimakasih.<br><br><br>
                        Post Master"; 

                        $this->sess_auth->send_message_erp($this->uri->segment_array(),$to, $cc, $subject, $content);
                }

            }

            $data['status']  = true;
            $data['last_id'] = $post['iMt01'];
            return json_encode($data);
        }
    


        //Ini Merupakan Standart Reject yang digunakan di erp
        function reject_view() {
            $echo = '<script type="text/javascript">
                         function submit_ajax(form_id) {
                            var remark = $("#sertifikat_remark").val();
                            if (remark=="") {
                                alert("Remark tidak boleh kosong ");
                                return
                            }

                            return $.ajax({
                                url: $("#"+form_id).attr("action"),
                                type: $("#"+form_id).attr("method"),
                                data: $("#"+form_id).serialize(),
                                success: function(data) {
                                    var o = $.parseJSON(data);
                                    var last_id = o.last_id;
                                    var url = "'.base_url().'processor/pengujian/sertifikat";                             
                                    if(o.status == true) { 
                                        $("#alert_dialog_form").dialog("close");
                                             $.get(url+"?action=update&id="+last_id, function(data) {
                                             $("div#form_sertifikat").html(data);
                                             
                                        });
                                        
                                    }
                                        reload_grid("grid_sertifikat");
                                }
                                
                             })
                         }
                     </script>';
            $echo .= '<h1>Reject</h1><br />';
            $echo .= '<form id="form_sertifikat_reject" action="'.base_url().'processor/pengujian/sertifikat?action=reject_process" method="post">';
            $echo .= '<div style="vertical-align: top;">';
            $echo .= 'Remark : 
                    <input type="hidden" name="iMt01" value="'.$this->input->get('iMt01').'" />
                    <input type="hidden" name="modul_id" value="'.$this->input->get('modul_id').'" />
                    <input type="hidden" name="level" value="'.$this->input->get('lvl').'" />
                    <input type="hidden" name="group_id" value="'.$this->input->get('group_id').'" />
                    
                    <textarea name="vRemark" id="reject_sertifikat_remark"></textarea>
            <button type="button" onclick="submit_ajax(\'form_sertifikat_reject\')">Reject</button>';
                
            $echo .= '</div>';
            $echo .= '</form>';
            return $echo;
        }


        
        function reject_process() {
            $post = $this->input->post();
            $cNip= $this->user->gNIP;
            $vName= $this->user->gName;
            $iMt01 = $post['iMt01'];
            $vRemark = $post['vRemark'];
            $lvl = $post['level'];

            //Letakan Query Update approve disini
            if($lvl==1){
                $dataupdate['cSphu_app']= $this->user->gNIP;
                $dataupdate['dSphu_app']= date('Y-m-d H:i:s');
                $dataupdate['vSphu_app']= $post['vRemark'];
                $dataupdate['iSphu_app']= 1;

                $subject = 'e-Pengujian -> Reject SPHU Sertifikat '.$rsql['vNo_transaksi'];
                $precontent = 'Admin SPHU telah melakukan Approval Permintaan Permohonan Kontrak Pengujian Mutu Obat Hewan baru';



            }else if($lvl==2){
                $dataupdate['cTu_app']= $this->user->gNIP;
                $dataupdate['dTu_app']= date('Y-m-d H:i:s');
                $dataupdate['vTu_app']= $post['vRemark'];
                $dataupdate['iTu_app']= 1;

                $subject = 'e-Pengujian -> Reject SPHU Sertifikat '.$rsql['vNo_transaksi'];
                $precontent = 'Admin TU telah melakukan Approval Permintaan Permohonan Kontrak Pengujian Mutu Obat Hewan baru';

            }else{
                $dataupdate['cFa_app']= $this->user->gNIP;
                $dataupdate['dFa_app']= date('Y-m-d H:i:s');
                $dataupdate['vFa_app']= $post['vRemark'];
                $dataupdate['iFa_app']= 1;

                $subject = 'e-Pengujian -> Reject SPHU Sertifikat '.$rsql['vNo_transaksi'];
                $precontent = 'Admin Keuangan telah melakukan Konfirmasi Permintaan Permohonan Kontrak Pengujian Mutu Obat Hewan baru';
            }
	        
	        $updet = $this->db->where('iMt01',$post['iMt01'])->update('bbpmsoh.mt01',$dataupdate);

            if($updet){
                $qsql="
                        select * 
                        from bbpmsoh.mt01 a 
                        join hrd.employee b on b.cNip=a.iCustomer
                        join bbpmsoh.m_tujuan_pengujian c on c.iM_tujuan_pengujian=a.iM_tujuan_pengujian
                        where a.lDeleted=0 
                        and a.iMt01 = '".$iMt01."'

                ";
                $rsql = $this->db->query($qsql)->row_array();

                $iAm = $this->whoAmI($this->user->gNIP);

                $to = $rsql['cNip_requestor'] ;                        
                $cc = $iAm['cNip'] ;

                $sqlEmpAr = 'select * from bbpmsoh.sysparam a where a.vVariable="MAIL_SERTIFIKAT_APP"';
                $dEmpAr =  $this->db->query($sqlEmpAr)->row_array();
                $sq= $dEmpAr['vContent'];
                $dataTO = $this->db->query($sq)->result_array();

                $to = '0';
                foreach ($dataTO as $toto) {
                    $to .=','.$toto['cNip'];
                }

                $bccMail = 'select * from bbpmsoh.sysparam a where a.vVariable="MAIL_BCC"';
                $dBcc =  $this->db->query($bccMail)->row_array();

                $to = $to;
                $cc = $this->user->gNIP.','.$dBcc['vContent'];

                
                $content="
                        <p>Diberitahukan bahwa ".$precontent." yang membutuhkan Follow up, dengan rincian sebagai berikut : <p>
                        <br><br>  
                        <table border='1' style='width: 750px;border-collapse: collapse;'>
                            <tr>
                                    <td style='width: 30%;'><b>Nomor Transaksi</b></td>
                                    <td> : ".$rsql['vNo_transaksi']."</td>
                            </tr>

                            <tr>
                                    <td style='width: 30%;'><b>Nama Pemohon</b></td>
                                    <td> : ".$rsql['cNip'].' || '.$rsql['vName']."</td>
                            </tr>


                            <tr>
                                    <td><b>No Permintaan</b></td>
                                    <td> : ".$rsql['vNomor']."</td>
                            </tr> 
                            <tr>
                                    <td><b>Perihal</b></td>
                                    <td> :".$rsql['vPerihal']."</td>
                            </tr> 

                            <tr>
                                    <td><b>Nama Perusahaan</b></td>
                                    <td> : ".$rsql['vName_company']."</td>
                            </tr> 

                            <tr>
                                    <td><b>Alamat</b></td>
                                    <td> : ".nl2br($rsql['vAddress_company'])."</td>
                            </tr>

                            <tr>
                                    <td><b>Nama Produsen</b></td>
                                    <td> : ".$rsql['vNama_produsen']."</td>
                            </tr> 

                            <tr>
                                    <td><b>Alamat Produsen</b></td>
                                    <td> : ".nl2br($rsql['vAlamat_produsen'])."</td>
                            </tr>

                            <tr>
                                    <td><b>Tujuan Pengujian Mutu</b></td>
                                    <td> : ".$rsql['vNama_tujuan']."</td>
                            </tr>

                            <tr>
                                    <td><b>Nama Sample</b></td>
                                    <td> : ".$rsql['vNama_sample']."</td>
                            </tr>

                            <tr>
                                    <td><b>Status</b></td>
                                    <td> : Reject</td>
                            </tr>



                            <tr>
                                    <td><b>Lokasi Modul</b></td>
                                    <td> e-Pengujian -> Transaksi -> Sertifikat</td>
                            </tr>
                            
                        </table> 

                    <br/> <br/>
                    Demikian, mohon segera follow up  pada aplikasi e-Pengujian. Terimakasih.<br><br><br>
                    Post Master"; 

                    $this->sess_auth->send_message_erp($this->uri->segment_array(),$to, $cc, $subject, $content);


            }

            $data['status']  = true;
            $data['last_id'] = $post['iMt01'];
            return json_encode($data);
        }


    //Standart Setiap table harus memiliki dCreated , cCreated, dUpdated, cUpdated
    function before_insert_processor($row, $postData) {
        $postData['dCreated'] = date('Y-m-d H:i:s');
        $postData['cCreated']=$this->user->gNIP;


        if($postData['isdraft']==true){
            $postData['iSubmit_sertifikat']=0;
        } else{
            $postData['iSubmit_sertifikat']=1;
        } 


        return $postData;

    }
    function before_update_processor($row, $postData) {
        $postData['dUpdated'] = date('Y-m-d H:i:s');
        $postData['cUpdated'] = $this->user->gNIP;

        if($postData['isdraft']==true){
            $postData['iSubmit_sertifikat']=0;
        } else{
            $postData['iSubmit_sertifikat']=1;
        } 


        return $postData; 
    }    

    function after_insert_processor($fields, $id, $postData) {
        //Example After Insert
        /*
        $cNip = $this->sess_auth->gNIP; 
        $sql = 'Place Query In Here';
        $this->dbset->query($sql);
        */
    }

    function after_update_processor($fields, $id, $postData) {
        //Example After Update
        /*
        $cNip = $this->sess_auth->gNIP; 
        $sql = 'Place Query In Here';
        $this->dbset->query($sql);
        */
        $qsql="
                select * 
                from bbpmsoh.mt01 a 
                join hrd.employee b on b.cNip=a.iCustomer
                join bbpmsoh.m_tujuan_pengujian c on c.iM_tujuan_pengujian=a.iM_tujuan_pengujian
                where a.lDeleted=0 
                and a.iMt01 = '".$iMt01."'

        ";
        $rsql = $this->db->query($qsql)->row_array();


        /*if($postData['iSubmit_sertifikat']==1){
                $subject = 'e-Pengujian -> Submit Sertifikat '.$rsql['vNo_transaksi'];
                $precontent = 'Admin Yanji telah melakukan Submit status sertifikat ';

                $qsql="
                        select * 
                        from bbpmsoh.mt01 a 
                        join hrd.employee b on b.cNip=a.iCustomer
                        join bbpmsoh.m_tujuan_pengujian c on c.iM_tujuan_pengujian=a.iM_tujuan_pengujian
                        where a.lDeleted=0 
                        and a.iMt01 = '".$iMt01."'

                ";
                $rsql = $this->db->query($qsql)->row_array();

                $iAm = $this->whoAmI($this->user->gNIP);

                $to = $rsql['cNip_requestor'] ;                        
                $cc = $iAm['cNip'] ;

                $sqlEmpAr = 'select * from bbpmsoh.sysparam a where a.vVariable="MAIL_SERTIFIKAT_APP_OTHER"';
                $dEmpAr =  $this->db->query($sqlEmpAr)->row_array();
                $sq= $dEmpAr['vContent'];
                $dataTO = $this->db->query($sq)->result_array();

                $to = '0';
                foreach ($dataTO as $toto) {
                    $to .=','.$toto['cNip'];
                }

                $bccMail = 'select * from bbpmsoh.sysparam a where a.vVariable="MAIL_BCC"';
                $dBcc =  $this->db->query($bccMail)->row_array();

                $to = $to;
                $cc = $this->user->gNIP.','.$dBcc['vContent'];

                
                $content="
                        <p>Diberitahukan bahwa ".$precontent." yang membutuhkan Follow up, dengan rincian sebagai berikut : <p>
                        <br><br>  
                        <table border='1' style='width: 750px;border-collapse: collapse;'>
                            <tr>
                                    <td style='width: 30%;'><b>Nomor Transaksi</b></td>
                                    <td> : ".$rsql['vNo_transaksi']."</td>
                            </tr>

                            <tr>
                                    <td style='width: 30%;'><b>Nama Pemohon</b></td>
                                    <td> : ".$rsql['cNip'].' || '.$rsql['vName']."</td>
                            </tr>


                            <tr>
                                    <td><b>No Permintaan</b></td>
                                    <td> : ".$rsql['vNomor']."</td>
                            </tr> 
                            <tr>
                                    <td><b>Perihal</b></td>
                                    <td> :".$rsql['vPerihal']."</td>
                            </tr> 

                            <tr>
                                    <td><b>Nama Perusahaan</b></td>
                                    <td> :".$rsql['vName_company']."</td>
                            </tr> 

                            <tr>
                                    <td><b>Alamat</b></td>
                                    <td> : ".nl2br($rsql['vAddress_company'])."</td>
                            </tr>

                            <tr>
                                    <td><b>Nama Produsen</b></td>
                                    <td> :".$rsql['vNama_produsen']."</td>
                            </tr> 

                            <tr>
                                    <td><b>Alamat Produsen</b></td>
                                    <td> : ".nl2br($rsql['vAlamat_produsen'])."</td>
                            </tr>

                            <tr>
                                    <td><b>Tujuan Pengujian Mutu</b></td>
                                    <td> : ".$rsql['vNama_tujuan']."</td>
                            </tr>

                            <tr>
                                    <td><b>Nama Sample</b></td>
                                    <td> : ".$rsql['vNama_sample']."</td>
                            </tr>  
                            <tr>
                                    <td><b>Status</b></td>
                                    <td> : Approve</td>
                            </tr>

                            <tr>
                                    <td><b>Lokasi Modul</b></td>
                                    <td> e-Pengujian -> Transaksi -> Sertifikat</td>
                            </tr>
                            
                        </table> 

                    <br/> <br/>
                    Demikian, mohon segera follow up  pada aplikasi e-Pengujian. Terimakasih.<br><br><br>
                    Post Master"; 

                    $this->sess_auth->send_message_erp($this->uri->segment_array(),$to, $cc, $subject, $content);


            

        }*/


    }

    function manipulate_insert_button($buttons) { 
        //Load Javascript In Here 
        $cNip= $this->user->gNIP;
        $js = $this->load->view('js/standard_js');
        $js .= $this->load->view('js/upload_js');

        $iframe = '<iframe name="sertifikat_frame" id="sertifikat_frame" height="0" width="0"></iframe>';
        
        $save_draft = '<button onclick="javascript:save_draft_btn_multiupload(\'sertifikat\', \' '.base_url().'processor/pengujian/sertifikat?draft=true \',this,true )"  id="button_save_draft_sertifikat"  class="ui-button-text icon-save" >Save as Draft</button>';
        $save = '<button onclick="javascript:save_btn_multiupload(\'sertifikat\', \' '.base_url().'processor/pengujian/sertifikat?company_id='.$this->input->get('company_id').'&group_id='.$this->input->get('group_id').'modul_id='.$this->input->get('modul_id').' \',this,true )"  id="button_save_submit_sertifikat"  class="ui-button-text icon-save" >Save &amp; Submit</button>';

        

        $buttons['save'] = $iframe.$save_draft.$save.$js;
        
        return $buttons;
    }

    function manipulate_update_button($buttons, $rowData) { 
        $peka=$rowData['iMt01'];


        //Load Javascript In Here 
        $cNip= $this->user->gNIP;
        $js = $this->load->view('js/standard_js');
        $js .= $this->load->view('js/upload_js');

        $iframe = '<iframe name="sertifikat_frame" id="sertifikat_frame" height="0" width="0"></iframe>';
        
        $update_draft = '<button onclick="javascript:update_draft_btn(\'sertifikat\', \' '.base_url().'processor/pengujian/sertifikat?draft=true \',this,true )"  id="button_update_draft_sertifikat"  class="ui-button-text icon-save" >Update as Draft</button>';
        $update = '<button onclick="javascript:update_btn_back(\'sertifikat\', \' '.base_url().'processor/pengujian/sertifikat?company_id='.$this->input->get('company_id').'&group_id='.$this->input->get('group_id').'modul_id='.$this->input->get('modul_id').' \',this,true )"  id="button_update_submit_sertifikat"  class="ui-button-text icon-save" >Update &amp; Submit</button>';

        $cekMT6 = 'select * from bbpmsoh.mt06 a where a.iMt01 = "'.$peka.'"';
        $dMt06 = $this->db->query($cekMT6)->row_array();



        if($dMt06['iDist_virologi']==1 or $dMt06['iDist_bakteri']==1 ){
        	// biologik
        	$templatenya = 'sertifikatB.docx';

        }else{
        	// farmastetik
        	$templatenya = 'sertifikatF.docx';
        }

        $grid          = $this->url;
		$url           = $this->masterUrl;

        $btnUpk  = "<button class='ui-button icon-print' onClick='btnUpk_{$this->url}(\"{$url}\", \"{$grid}\", this)'>Print</button>";
		$btnUpk .= "<script>
						function btnUpk_{$this->url}(url, grid, dis) {

							custom_confirm('Print Dokumen ?', function() {
								template = '$templatenya';
								var loadFile = function(url, callback) {
									JSZipUtils.getBinaryContent(url, callback);
								}
								loadFile('../files/pengujian/template/'+template, function(err, content) {
									if (err) {throw e};

									$.ajax({
										url: url+'&action=getDataMemo',
										type: 'POST',
										dataType: 'json',
										data: '&id={$peka}',
										success: function(data) {

											doc = new Docxgen(content);

											doc.setData({
												'NAMA_PEMOHON' : data[0].NAMA_PEMOHON,
												'ALAMAT_PEMOHON' : data[0].ALAMAT_PEMOHON,
												'NAMA_PRODUSEN' : data[0].NAMA_PRODUSEN,
												'ALAMAT_PRODUSEN' : data[0].ALAMAT_PRODUSEN,
												'KADALUARSA' : data[0].KADALUARSA,
												'NOREG' : data[0].NOREG,
												'KEMASAN' : data[0].KEMASAN,
												'JENIS' : data[0].JENIS,
												'NOMOR_UJI' : data[0].NOMOR_UJI
		    									
											})

											doc.render()
		    								out = doc.getZip().generate({type:'blob'})

		    								nmdok = 'Sertifikat';
		    								saveAs(out, nmdok+' - ' + data[0].NOMOR_UJI + '.docx')
										}
									})
								})
							})
						}
					</script>";


        if ($this->input->get('action') == 'view') {
            unset($buttons['update']);
            $buttons['update'] = $btnUpk;    
            
        }
        else{ 
        	unset($buttons['update']);
        	 /*
            idprivi_group;vNamaGroup
			1;Administrator
			2;Admini Yanji
			3;Admin Biologik
			4;Admin Virologi
			5;Admin Farmastetik & Premiks
			6;Admin SPHU
			7;Customer
			8;Kepala Balai
			9;TU
			10;Keuangan



        */ 

        	$groupnya = $this->checkgroup($this->user->gNIP);             
	        if( $groupnya['idprivi_group']== 2 and $rowData['iSubmit_sertifikat']==0 ){
	            $buttons['update'] = $iframe.$update_draft.$update.$js;    
	        }else if($groupnya['idprivi_group']== 6 and $rowData['iSubmit_sertifikat']==1 and $rowData['iSphu_app']==0){
	        	$approve = '<button onclick="javascript:load_popup(\' '.base_url().'processor/pengujian/sertifikat?action=approve&level=1&iMt01='.$peka.'&company_id='.$this->input->get('company_id').'&group_id='.$this->input->get('group_id').'&modul_id='.$this->input->get('modul_id').' \')"  id="button_approve_sertifikat"  class="ui-button-text icon-save" >Approve</button>';
        		$reject = '<button onclick="javascript:load_popup(\' '.base_url().'processor/pengujian/sertifikat?action=reject&level=1&iMt01='.$peka.'&company_id='.$this->input->get('company_id').'&group_id='.$this->input->get('group_id').'&modul_id='.$this->input->get('modul_id').' \' )"  id="button_reject_sertifikat"  class="ui-button-text icon-save" >Reject</button>';
        		$buttons['update'] = $iframe.$approve.$reject;    

	        }else if($groupnya['idprivi_group']== 9 and $rowData['iSphu_app']==2 and $rowData['iTu_app']==0){
	        	$approve = '<button onclick="javascript:load_popup(\' '.base_url().'processor/pengujian/sertifikat?action=approve&level=2&iMt01='.$peka.'&company_id='.$this->input->get('company_id').'&group_id='.$this->input->get('group_id').'&modul_id='.$this->input->get('modul_id').' \')"  id="button_approve_sertifikat"  class="ui-button-text icon-save" >Approve</button>';
        		$reject = '<button onclick="javascript:load_popup(\' '.base_url().'processor/pengujian/sertifikat?action=reject&level=2&iMt01='.$peka.'&company_id='.$this->input->get('company_id').'&group_id='.$this->input->get('group_id').'&modul_id='.$this->input->get('modul_id').' \' )"  id="button_reject_sertifikat"  class="ui-button-text icon-save" >Reject</button>';
        		$buttons['update'] = $iframe.$approve.$reject;    
	        }else if($groupnya['idprivi_group']== 10 and $rowData['iTu_app']==2 and $rowData['iFa_app']==0){
	        	$approve = '<button onclick="javascript:load_popup(\' '.base_url().'processor/pengujian/sertifikat?action=approve&level=3&iMt01='.$peka.'&company_id='.$this->input->get('company_id').'&group_id='.$this->input->get('group_id').'&modul_id='.$this->input->get('modul_id').' \')"  id="button_approve_sertifikat"  class="ui-button-text icon-save" >Confirm</button>';
        		$reject = '<button onclick="javascript:load_popup(\' '.base_url().'processor/pengujian/sertifikat?action=reject&level=3&iMt01='.$peka.'&company_id='.$this->input->get('company_id').'&group_id='.$this->input->get('group_id').'&modul_id='.$this->input->get('modul_id').' \' )"  id="button_reject_sertifikat"  class="ui-button-text icon-save" >Reject</button>';
        		$buttons['update'] = $iframe.$approve;    
	        }

            
        }
        
        return $buttons;
    }

    function whoAmI($nip) { 
        $sql = 'select b.vDescription as vdepartemen,a.*,b.*
                        from hrd.employee a 
                        join hrd.msdepartement b on b.iDeptID=a.iDepartementID
                        join hrd.position c on c.iPostId=a.iPostID
                        where a.cNip ="'.$nip.'"
                        ';
        
        $data = $this->db->query($sql)->row_array();
        return $data;
    }

    function download($vFilename) { 
        $this->load->helper('download');        
        $name = $vFilename;
        $id = $_GET['id'];
        $tempat = $_GET['path'];    
        $path = file_get_contents('./files/pengujian/'.$tempat.'/'.$id.'/'.$name);    
        force_download($name, $path);


    }

    //Output
    public function output(){
        $this->index($this->input->get('action'));
    }

}
